#!/usr/bin/env python3
"""Generate original CC0 hero + pet art for Paloria (AT-D).

hero_sheet.png: 64x112 (4 cols x 7 rows, 16x16 frames)
  cols: down / up / left / right
  rows: walk 0-3, attack windup 4, attack strike 5, roll 6
palfox_sheet.png: 64x64 (4 cols x 4 rows, 16x16 frames)
  rows: down / up / left / right ; cols: idle + walk cycle

Provenance: GENERATED by project tool, CC0-1.0, "Paloria project".
"""
import argparse
import os

from PIL import Image, ImageDraw

PAL = {
    "K": (29, 36, 51),
    "hair": (46, 58, 92),
    "hairl": (74, 95, 138),
    "skin": (242, 200, 155),
    "skind": (210, 160, 120),
    "jacket": (201, 111, 46),
    "jacketd": (142, 74, 30),
    "scarf": (240, 230, 210),
    "scarfd": (217, 201, 168),
    "gold": (242, 194, 48),
    "pants": (59, 59, 74),
    "boots": (107, 74, 46),
    "stick": (169, 116, 79),
    "fox": (232, 150, 80),
    "foxd": (190, 110, 55),
    "cream": (247, 235, 210),
}


def C(n):
    return PAL[n] + (255,)


def new_frame():
    return Image.new("RGBA", (16, 16), (0, 0, 0, 0))


def px(d, x, y, c):
    if 0 <= x < 16 and 0 <= y < 16:
        d.point((x, y), fill=C(c))


def rect(d, x0, y0, x1, y1, c):
    d.rectangle([x0, y0, x1, y1], fill=C(c))


# ------------------------------------------------------------------ hero
def draw_head(d, facing):
    # head base
    rect(d, 4, 2, 11, 7, "skin")
    rect(d, 4, 2, 11, 3, "skind")
    # hair cap
    for x in range(3, 13):
        px(d, x, 1, "hair")
    rect(d, 3, 2, 12, 3, "hair")
    px(d, 4, 1, "hairl")
    px(d, 7, 1, "hairl")
    if facing == "down":
        px(d, 3, 4, "hair")
        px(d, 12, 4, "hair")
        px(d, 6, 5, "K")
        px(d, 9, 5, "K")
        px(d, 7, 6, "skind")
        px(d, 8, 6, "skind")
    elif facing == "up":
        rect(d, 4, 4, 11, 7, "hair")
        px(d, 6, 5, "hairl")
        px(d, 9, 5, "hairl")
    elif facing in ("left", "right"):
        ex = 5 if facing == "left" else 10
        px(d, ex, 5, "K")
        px(d, 3 if facing == "left" else 12, 4, "hair")
        px(d, 6 if facing == "left" else 9, 6, "skind")


def draw_hero(facing, pose):
    """pose: ('walk', step) | ('windup',) | ('strike',) | ('roll',)."""
    img = new_frame()
    d = ImageDraw.Draw(img)
    bob = 0
    if pose[0] == "walk":
        step = pose[1]
        bob = 0 if step % 2 == 0 else -1
    if pose[0] == "roll":
        # tucked roll: round body
        d.ellipse([3, 5, 13, 15], fill=C("K"))
        d.ellipse([4, 6, 12, 14], fill=C("jacket"))
        d.ellipse([5, 4, 11, 9], fill=C("K"))
        d.ellipse([6, 5, 10, 8], fill=C("hair"))
        px(d, 5, 10, "scarf")
        px(d, 10, 10, "scarf")
        return img
    # scarf (behind neck, tail sways with walk)
    sway = 0
    if pose[0] == "walk":
        sway = [-1, 0, 1, 0][pose[1]]
    rect(d, 4, 8 + bob, 11, 9 + bob, "scarf")
    for i in range(3):
        px(d, 5 + i + sway, 10 + bob + i // 2, "scarfd")
    # torso
    rect(d, 5, 9 + bob, 10, 12 + bob, "jacket")
    rect(d, 5, 9 + bob, 6, 12 + bob, "jacketd")
    px(d, 9, 10 + bob, "gold")  # star pin
    # legs
    leg_l = leg_r = 0
    if pose[0] == "walk":
        leg_l, leg_r = [(0, 0), (-1, 1), (0, 0), (1, -1)][pose[1]]
    for lx, off in ((6, leg_l), (9, leg_r)):
        rect(d, lx, 12 + bob + min(off, 0), lx + 1, 14 + bob + max(off, 0), "pants")
        rect(d, lx, 14 + bob + max(off, 0), lx + 1, 15 + bob + max(off, 0), "boots")
    # arms + tool
    if pose[0] == "windup":
        # right arm raised with stick
        rect(d, 11, 5 + bob, 12, 9 + bob, "jacket")
        d.line([(12, 5 + bob), (14, 1)], fill=C("stick"), width=2)
        px(d, 14, 0, "gold")
        rect(d, 3, 9 + bob, 4, 11 + bob, "jacketd")
    elif pose[0] == "strike":
        dx = {"down": (0, 1), "up": (0, -1), "left": (-1, 0), "right": (1, 0)}[facing]
        if facing in ("down", "up"):
            rect(d, 7, 9 + bob, 8, 12 + bob, "jacket")
            x0, y0 = 7, 12 + bob if facing == "down" else 8 + bob
            d.line([(x0, y0), (x0, y0 + dx[1] * 5)], fill=C("stick"), width=2)
        else:
            ax = 11 if facing == "right" else 4
            rect(d, ax, 9 + bob, ax + 1, 11 + bob, "jacket")
            x0 = 13 if facing == "right" else 2
            d.line([(x0, 10 + bob), (x0 + dx[0] * 4, 10 + bob)], fill=C("stick"), width=2)
        rect(d, 3, 9 + bob, 4, 11 + bob, "jacketd")
    else:
        rect(d, 3, 9 + bob, 4, 11 + bob, "jacketd")
        rect(d, 11, 9 + bob, 12, 11 + bob, "jacket")
    draw_head(d, facing)
    return img


def hero_sheet():
    sheet = Image.new("RGBA", (64, 112), (0, 0, 0, 0))
    facings = ["down", "up", "left", "right"]
    rows = [("walk", 0), ("walk", 1), ("walk", 2), ("walk", 3),
            ("windup",), ("strike",), ("roll",)]
    for r, pose in enumerate(rows):
        for c, facing in enumerate(facings):
            sheet.paste(draw_hero(facing, pose), (c * 16, r * 16))
    return sheet


# ------------------------------------------------------------------ palfox
def draw_palfox(facing, step):
    img = new_frame()
    d = ImageDraw.Draw(img)
    hop = 0 if step % 2 == 0 else -1
    # tail (fluffy, cream tip)
    tx = {"down": 11, "up": 4, "left": 11, "right": 4}[facing]
    d.ellipse([tx - 2, 8 + hop, tx + 3, 13 + hop], fill=C("K"))
    d.ellipse([tx - 1, 9 + hop, tx + 2, 12 + hop], fill=C("fox"))
    px(d, tx + (2 if facing in ("down", "left") else -2), 10 + hop, "cream")
    # body
    d.ellipse([4, 7 + hop, 11, 13 + hop], fill=C("K"))
    d.ellipse([5, 8 + hop, 10, 12 + hop], fill=C("fox"))
    rect(d, 5, 10 + hop, 10, 12 + hop, "cream")
    # head
    d.ellipse([4, 2 + hop, 11, 8 + hop], fill=C("K"))
    d.ellipse([5, 3 + hop, 10, 7 + hop], fill=C("fox"))
    # ears
    for ex in (5, 9):
        d.polygon([(ex, 3 + hop), (ex + 2, 3 + hop), (ex + 1, 0 + hop)], fill=C("K"))
        d.polygon([(ex, 2 + hop), (ex + 2, 2 + hop), (ex + 1, 1 + hop)], fill=C("foxd"))
    # face
    if facing == "down":
        px(d, 6, 5 + hop, "K")
        px(d, 9, 5 + hop, "K")
        px(d, 7, 6 + hop, "K")
    elif facing == "up":
        rect(d, 5, 3 + hop, 10, 5 + hop, "foxd")
    else:
        ex = 6 if facing == "left" else 9
        px(d, ex, 5 + hop, "K")
        px(d, ex, 6 + hop, "skind" if False else "K")
    # legs
    lo = [0, -1, 0, 1][step]
    for lx in (5, 9):
        rect(d, lx, 12 + hop, lx + 1, 14 + hop + (lo if lx == 5 else -lo), "foxd")
    return img


def palfox_sheet():
    sheet = Image.new("RGBA", (64, 64), (0, 0, 0, 0))
    for r, facing in enumerate(["down", "up", "left", "right"]):
        for c in range(4):
            sheet.paste(draw_palfox(facing, c), (c * 16, r * 16))
    return sheet


# ------------------------------------------------------------------ npcs
NPC_PALETTES = {
    "elder": {"hair": (200, 200, 210), "top": (122, 95, 160), "topd": (90, 70, 125),
              "skin": (235, 190, 150), "acc": (150, 110, 70)},
    "merchant": {"hair": (90, 60, 40), "top": (70, 130, 90), "topd": (50, 95, 65),
                 "skin": (242, 200, 155), "acc": (240, 230, 210)},
    "kid": {"hair": (60, 50, 70), "top": (230, 120, 90), "topd": (185, 90, 60),
            "skin": (245, 210, 170), "acc": (242, 194, 48)},
}


def draw_npc(variant, facing, step):
    P = NPC_PALETTES[variant]
    img = new_frame()
    d = ImageDraw.Draw(img)
    hop = 0 if step % 2 == 0 else -1
    scale = 0.85 if variant == "kid" else 1.0
    # body
    bw = int(8 * scale)
    x0 = 8 - bw // 2
    d.ellipse([x0, 6 + hop, x0 + bw, 13 + hop], fill=(29, 36, 51, 255))
    d.ellipse([x0 + 1, 7 + hop, x0 + bw - 1, 12 + hop], fill=P["top"] + (255,))
    rect(d, x0 + 1, 7 + hop, x0 + 2, 12 + hop, "K") if False else None
    # head
    hw = int(8 * scale)
    hx0 = 8 - hw // 2
    rect(d, hx0, 1 + hop, hx0 + hw - 1, 6 + hop, "K")
    rect(d, hx0 + 1, 2 + hop, hx0 + hw - 2, 5 + hop, "skin")
    # hair
    for x in range(hx0, hx0 + hw):
        px(d, x, 1 + hop, "hair")
    rect(d, hx0, 2 + hop, hx0 + hw - 1, 2 + hop, "hair")
    if variant == "elder":
        px(d, hx0 + hw // 2, 0 + hop, "hair")  # bun
    # face
    if facing == "down":
        px(d, hx0 + 2, 4 + hop, "K")
        px(d, hx0 + hw - 3, 4 + hop, "K")
    elif facing in ("left", "right"):
        ex = hx0 + 2 if facing == "left" else hx0 + hw - 3
        px(d, ex, 4 + hop, "K")
    # merchant apron / elder cane / kid star
    acc = P["acc"] + (255,)
    if variant == "merchant":
        d.rectangle([x0 + 2, 8 + hop, x0 + bw - 3, 12 + hop], fill=acc)
    elif variant == "elder":
        d.line([(x0 + bw + 1, 6 + hop), (x0 + bw + 1, 13 + hop)], fill=acc, width=1)
    else:
        d.point((8, 9 + hop), fill=acc)
    if variant == "kid":
        d.rectangle([hx0 - 1, 0 + hop, hx0 + hw, 1 + hop], fill=acc)  # cap
    # legs
    lo = [0, -1, 0, 1][step]
    for lx in (6, 9):
        rect(d, lx, 12 + hop, lx + 1, 14 + hop + (lo if lx == 6 else -lo), "K")
    return img


def npc_sheet(variant):
    sheet = Image.new("RGBA", (64, 64), (0, 0, 0, 0))
    for r, facing in enumerate(["down", "up", "left", "right"]):
        for c in range(4):
            sheet.paste(draw_npc(variant, facing, c), (c * 16, r * 16))
    return sheet


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    os.makedirs(args.out, exist_ok=True)
    hero_sheet().save(os.path.join(args.out, "hero_sheet.png"))
    palfox_sheet().save(os.path.join(args.out, "palfox_sheet.png"))
    for variant in ("elder", "merchant", "kid"):
        npc_sheet(variant).save(os.path.join(args.out, "npc_%s.png" % variant))
    print("generated hero + palfox + npc sheets ->", args.out)


if __name__ == "__main__":
    main()

