#!/usr/bin/env python3
"""Generate original CC0 town art for Paloria Luminous Town (AT-B).

Top-down/oblique pixel-style buildings drawn with PIL from the AT palette
(see docs/assets/AT_ART_DIRECTION.md). Provenance: GENERATED by project tool,
license CC0-1.0, author "Paloria project".

Usage:
    python3 tools/generate_town_art.py --out /tmp/paloria_town
"""
import argparse
import json
import os

from PIL import Image, ImageDraw

PAL = {
    "K": (29, 36, 51),      # outline
    "roof": (63, 95, 138),  # roof_blue
    "roofd": (44, 68, 99),  # roof_shadow
    "plas": (240, 230, 210),# plaster
    "plasd": (217, 201, 168),# plaster_shadow
    "torii": (192, 57, 43), # torii_red
    "toriid": (142, 42, 32),
    "paper": (247, 217, 160),# lantern_paper
    "glow": (255, 179, 71), # lantern_glow
    "sakura": (242, 167, 195),
    "sakurad": (214, 127, 158),
    "wood": (169, 116, 79),
    "woodd": (122, 82, 51),
    "stone": (154, 163, 178),
    "stoned": (107, 114, 128),
    "water": (63, 167, 214),
    "waterd": (36, 116, 163),
    "leaf": (79, 174, 79),
    "leafd": (47, 125, 58),
    "gold": (242, 194, 48),
    "red": (214, 64, 94),
    "snow": (238, 243, 248),
    "night": (43, 51, 85),
}


def C(name):
    return PAL[name] + (255,)


def new(w, h):
    return Image.new("RGBA", (w, h), (0, 0, 0, 0))


def orect(d, x0, y0, x1, y1, fill, outline="K", ow=2):
    d.rectangle([x0, y0, x1, y1], fill=C(outline))
    d.rectangle([x0 + ow, y0 + ow, x1 - ow, y1 - ow], fill=C(fill))


def roof_poly(d, points, fill="roof", shade="roofd"):
    d.polygon(points, fill=C("K"))
    inset = [(x, y) for x, y in points]
    # simple inset by moving toward centroid
    cx = sum(p[0] for p in points) / len(points)
    cy = sum(p[1] for p in points) / len(points)
    inset = [(x + (cx - x) * 0.08, y + (cy - y) * 0.08) for x, y in points]
    d.polygon(inset, fill=C(fill))


# ---------------------------------------------------------------- houses
def house_a():
    """128x112 town house: plaster walls, blue tile roof, door + windows."""
    img = new(128, 112)
    d = ImageDraw.Draw(img)
    # walls
    orect(d, 24, 48, 104, 104, "plas")
    d.rectangle([26, 50, 102, 58], fill=C("plasd"))  # top shade
    # door
    orect(d, 56, 72, 76, 104, "woodd")
    d.rectangle([58, 74, 62, 102], fill=C("wood"))
    d.ellipse([70, 88, 74, 92], fill=C("gold"))  # knob
    # windows
    for x in (32, 88):
        orect(d, x, 64, x + 16, 80, "night")
        d.rectangle([x + 2, 66, x + 6, 78], fill=C("snow"))
    # roof: trapezoid with tile lines
    d.polygon([(12, 52), (64, 8), (116, 52)], fill=C("K"))
    d.polygon([(18, 50), (64, 14), (110, 50)], fill=C("roof"))
    for y in range(20, 48, 7):
        t = (y - 8) / 44.0
        x0 = int(64 - (64 - 14) * t)
        x1 = int(64 + (64 - 14) * t)
        d.line([(x0, y), (x1, y)], fill=C("roofd"))
    # ridge
    d.rectangle([58, 6, 70, 12], fill=C("K"))
    d.rectangle([60, 8, 68, 10], fill=C("roofd"))
    return img


def house_b():
    img = house_a()
    d = ImageDraw.Draw(img)
    # shop variant: awning + sign
    d.polygon([(20, 56), (108, 56), (100, 72), (28, 72)], fill=C("K"))
    for i in range(6):
        x0 = 24 + i * 14
        col = "red" if i % 2 == 0 else "snow"
        d.polygon([(x0, 58), (x0 + 14, 58), (x0 + 12, 70), (x0 + 2, 70)], fill=C(col))
    return img


# ---------------------------------------------------------------- station
def station_hall():
    """220x120 station hall with clock and platform canopy."""
    img = new(220, 120)
    d = ImageDraw.Draw(img)
    orect(d, 20, 40, 200, 108, "plas")
    d.rectangle([22, 42, 198, 50], fill=C("plasd"))
    # long roof
    d.polygon([(8, 44), (110, 6), (212, 44)], fill=C("K"))
    d.polygon([(16, 42), (110, 12), (204, 42)], fill=C("roof"))
    for y in range(18, 40, 6):
        t = (y - 6) / 38.0
        d.line([(int(110 - 94 * t), y), (int(110 + 94 * t), y)], fill=C("roofd"))
    # windows row
    for x in range(32, 190, 28):
        orect(d, x, 60, x + 18, 82, "night")
        d.rectangle([x + 2, 62, x + 6, 80], fill=C("snow"))
    # central door
    orect(d, 100, 78, 122, 108, "woodd")
    # sign board with star
    orect(d, 88, 44, 134, 58, "woodd")
    _star(d, 110, 51, 6, "gold")
    # clock
    d.ellipse([146, 84, 170, 108], fill=C("K"))
    d.ellipse([148, 86, 168, 106], fill=C("snow"))
    d.line([(158, 96), (158, 90)], fill=C("K"))
    d.line([(158, 96), (163, 96)], fill=C("K"))
    return img


def _star(d, cx, cy, r, col):
    import math
    pts = []
    for i in range(10):
        ang = -math.pi / 2 + i * math.pi / 5
        rr = r if i % 2 == 0 else r * 0.45
        pts.append((cx + rr * math.cos(ang), cy + rr * math.sin(ang)))
    d.polygon(pts, fill=C(col))


def clock_tower():
    """64x160 clock tower."""
    img = new(64, 160)
    d = ImageDraw.Draw(img)
    orect(d, 16, 40, 48, 152, "plas")
    d.rectangle([18, 42, 30, 150], fill=C("plasd"))
    # clock face
    d.ellipse([14, 48, 50, 84], fill=C("K"))
    d.ellipse([17, 51, 47, 81], fill=C("snow"))
    for ang in range(0, 360, 30):
        import math
        r1, r2 = 12, 15
        a = math.radians(ang)
        d.line([(32 + r1 * math.cos(a), 66 + r1 * math.sin(a)),
                (32 + r2 * math.cos(a), 66 + r2 * math.sin(a))], fill=C("K"))
    d.line([(32, 66), (32, 58)], fill=C("red"))
    d.line([(32, 66), (38, 66)], fill=C("K"))
    # belfry + spire
    orect(d, 12, 20, 52, 40, "woodd")
    d.polygon([(32, 2), (54, 22), (10, 22)], fill=C("K"))
    d.polygon([(32, 6), (50, 20), (14, 20)], fill=C("roof"))
    _star(d, 32, 30, 5, "gold")
    # door
    orect(d, 26, 120, 38, 152, "woodd")
    return img


def platform():
    """320x40 platform edge."""
    img = new(320, 40)
    d = ImageDraw.Draw(img)
    d.rectangle([0, 0, 319, 39], fill=C("K"))
    d.rectangle([2, 2, 317, 37], fill=C("stone"))
    for x in range(2, 318, 24):
        d.line([(x, 2), (x, 37)], fill=C("stoned"))
    d.rectangle([2, 2, 317, 8], fill=C("snow"))  # edge line
    d.rectangle([2, 8, 317, 11], fill=C("gold"))  # warning strip
    return img


# ---------------------------------------------------------------- market
def stall():
    """96x64 market stall with striped awning."""
    img = new(96, 64)
    d = ImageDraw.Draw(img)
    # posts
    for x in (10, 82):
        d.rectangle([x, 18, x + 5, 60], fill=C("K"))
        d.rectangle([x + 1, 19, x + 4, 59], fill=C("wood"))
    # awning
    d.polygon([(4, 20), (92, 20), (84, 2), (12, 2)], fill=C("K"))
    for i in range(8):
        x0 = 8 + i * 10
        col = "red" if i % 2 == 0 else "snow"
        d.polygon([(x0, 18), (x0 + 10, 18), (x0 + 9, 4), (x0 + 1, 4)], fill=C(col))
    # counter
    orect(d, 12, 38, 84, 60, "wood")
    d.rectangle([14, 40, 82, 44], fill=C("woodd"))
    # goods: fruit + boxes
    for x, col in [(20, "red"), (32, "gold"), (44, "leaf")]:
        d.ellipse([x, 30, x + 10, 38], fill=C(col))
        d.ellipse([x, 30, x + 10, 38], outline=C("K"))
    orect(d, 60, 30, 78, 38, "paper")
    return img


def bulletin():
    """48x64 bulletin board."""
    img = new(48, 64)
    d = ImageDraw.Draw(img)
    for x in (6, 38):
        d.rectangle([x, 30, x + 5, 62], fill=C("K"))
        d.rectangle([x + 1, 31, x + 4, 61], fill=C("woodd"))
    orect(d, 2, 4, 46, 34, "wood")
    for i, (x, y) in enumerate([(8, 10), (24, 10), (8, 22), (24, 22)]):
        orect(d, x, y, x + 12, y + 8, "snow" if i % 2 else "paper")
    _star(d, 24, 4 - 6, 4, "gold")
    return img


def vending():
    """40x64 vending machine with lit front."""
    img = new(40, 64)
    d = ImageDraw.Draw(img)
    orect(d, 4, 4, 36, 60, "red")
    orect(d, 8, 10, 32, 34, "night")
    for y in (14, 22, 30):
        for x, col in [(11, "red"), (17, "gold"), (23, "water")]:
            d.rectangle([x, y, x + 4, y + 5], fill=C(col))
    d.rectangle([9, 11, 13, 33], fill=C("snow"))
    orect(d, 8, 40, 32, 52, "snow")
    d.rectangle([10, 42, 30, 44], fill=C("K"))
    return img


# ---------------------------------------------------------------- shrine
def torii():
    """96x96 torii gate."""
    img = new(96, 96)
    d = ImageDraw.Draw(img)
    for x in (22, 66):
        d.rectangle([x, 28, x + 9, 94], fill=C("K"))
        d.rectangle([x + 2, 30, x + 7, 92], fill=C("torii"))
        d.rectangle([x + 2, 30, x + 4, 92], fill=C("toriid"))
    # top lintel (curved)
    d.polygon([(8, 26), (88, 26), (84, 10), (12, 10)], fill=C("K"))
    d.polygon([(11, 24), (85, 24), (82, 12), (14, 12)], fill=C("torii"))
    # second lintel
    d.rectangle([14, 34, 82, 42], fill=C("K"))
    d.rectangle([16, 36, 80, 40], fill=C("torii"))
    # center plaque
    orect(d, 42, 14, 54, 24, "toriid")
    _star(d, 48, 19, 4, "gold")
    return img


def shrine_hall():
    """192x128 shrine hall with sweeping roof."""
    img = new(192, 128)
    d = ImageDraw.Draw(img)
    # stairs
    for i in range(3):
        d.rectangle([70 + i * 4, 108 + i * 5, 122 - i * 4, 112 + i * 5], fill=C("K"))
        d.rectangle([72 + i * 4, 109 + i * 5, 120 - i * 4, 111 + i * 5], fill=C("stone"))
    # body
    orect(d, 56, 56, 136, 110, "toriid")
    d.rectangle([58, 58, 134, 66], fill=C("torii"))
    # doors
    orect(d, 84, 76, 108, 110, "woodd")
    d.rectangle([86, 78, 92, 108], fill=C("wood"))
    # paper lanterns hanging
    for x in (64, 128):
        d.line([(x, 56), (x, 62)], fill=C("K"))
        d.ellipse([x - 7, 62, x + 7, 76], fill=C("K"))
        d.ellipse([x - 5, 64, x + 5, 74], fill=C("paper"))
    # grand roof
    d.polygon([(24, 60), (96, 10), (168, 60)], fill=C("K"))
    d.polygon([(30, 58), (96, 16), (162, 58)], fill=C("roofd"))
    # curved eaves
    d.polygon([(16, 62), (96, 22), (176, 62), (168, 68), (96, 30), (24, 68)], fill=C("K"))
    d.polygon([(22, 62), (96, 26), (170, 62), (164, 65), (96, 32), (28, 65)], fill=C("roof"))
    _star(d, 96, 40, 7, "gold")
    return img


def stone_lantern():
    """24x48 stone lantern."""
    img = new(24, 48)
    d = ImageDraw.Draw(img)
    d.ellipse([4, 30, 20, 44], fill=C("K"))
    d.ellipse([5, 31, 19, 43], fill=C("stone"))
    d.rectangle([9, 24, 15, 31], fill=C("K"))
    d.rectangle([10, 25, 14, 30], fill=C("stoned"))
    d.ellipse([5, 12, 19, 26], fill=C("K"))
    d.ellipse([6, 13, 18, 25], fill=C("paper"))
    d.polygon([(12, 2), (20, 12), (4, 12)], fill=C("K"))
    d.polygon([(12, 5), (18, 11), (6, 11)], fill=C("stone"))
    return img


# ---------------------------------------------------------------- water
def lake():
    """420x260 lake with sandy shore."""
    img = new(420, 260)
    d = ImageDraw.Draw(img)
    d.ellipse([4, 4, 416, 256], fill=C("K"))
    d.ellipse([10, 10, 410, 250], fill=C("plasd"))  # sand
    d.ellipse([26, 26, 394, 234], fill=C("water"))
    import random
    rng = random.Random(9)
    for _ in range(40):
        x, y = rng.randint(40, 380), rng.randint(40, 220)
        if ((x - 210) / 190) ** 2 + ((y - 130) / 110) ** 2 < 1:
            d.line([(x, y), (x + 8, y)], fill=C("snow"))
    for _ in range(12):
        x, y = rng.randint(40, 380), rng.randint(40, 220)
        if ((x - 210) / 190) ** 2 + ((y - 130) / 110) ** 2 < 1:
            d.line([(x, y), (x + 5, y + 2)], fill=C("waterd"))
    return img


def bridge():
    """160x48 wooden foot bridge."""
    img = new(160, 48)
    d = ImageDraw.Draw(img)
    # arc deck
    d.polygon([(4, 40), (156, 40), (156, 30), (4, 30)], fill=C("K"))
    for x in range(6, 156, 12):
        top = 30 - int(6 * (1 - abs(x - 80) / 80))
        d.rectangle([x, top, x + 10, 38], fill=C("wood"))
        d.rectangle([x, top, x + 10, top + 2], fill=C("woodd"))
    # rails
    for y in (14, 18):
        d.rectangle([4, y, 156, y + 3], fill=C("K"))
        d.rectangle([5, y + 1, 155, y + 2], fill=C("wood"))
    for x in range(10, 156, 24):
        d.rectangle([x, 14, x + 4, 32], fill=C("K"))
        d.rectangle([x + 1, 15, x + 3, 31], fill=C("woodd"))
    return img


def dock():
    """96x32 wooden dock."""
    img = new(96, 32)
    d = ImageDraw.Draw(img)
    d.rectangle([2, 6, 94, 26], fill=C("K"))
    for x in range(4, 94, 14):
        d.rectangle([x, 8, x + 12, 24], fill=C("wood"))
        d.rectangle([x, 8, x + 12, 10], fill=C("woodd"))
    for x in (8, 82):
        d.rectangle([x, 22, x + 6, 32], fill=C("K"))
        d.rectangle([x + 1, 23, x + 5, 31], fill=C("woodd"))
    return img


def town_gate():
    """48x96 stone gate pillars with beam."""
    img = new(48, 96)
    d = ImageDraw.Draw(img)
    for x in (4, 34):
        orect(d, x, 30, x + 10, 94, "stone")
        d.rectangle([x + 2, 32, x + 4, 92], fill=C("stoned"))
        d.polygon([(x - 2, 30), (x + 12, 30), (x + 5, 20)], fill=C("K"))
        d.polygon([(x, 28), (x + 10, 28), (x + 5, 22)], fill=C("stone"))
    d.rectangle([0, 8, 48, 20], fill=C("K"))
    d.rectangle([2, 10, 46, 18], fill=C("wood"))
    _star(d, 24, 14, 5, "gold")
    return img


# ---------------------------------------------------------------- props
def power_pole():
    """32x96 power pole."""
    img = new(32, 96)
    d = ImageDraw.Draw(img)
    d.rectangle([13, 8, 19, 94], fill=C("K"))
    d.rectangle([14, 9, 18, 93], fill=C("woodd"))
    d.rectangle([15, 9, 16, 93], fill=C("wood"))
    d.rectangle([4, 14, 28, 19], fill=C("K"))
    d.rectangle([5, 15, 27, 18], fill=C("woodd"))
    for x in (7, 23):
        d.ellipse([x - 2, 17, x + 2, 22], fill=C("K"))
    return img


def sakura_tree():
    """64x80 sakura tree."""
    img = new(64, 80)
    d = ImageDraw.Draw(img)
    import random
    rng = random.Random(21)
    d.rectangle([29, 48, 35, 78], fill=C("K"))
    d.rectangle([30, 49, 34, 77], fill=C("woodd"))
    for (x, y, r) in [(32, 26, 20), (18, 34, 12), (46, 34, 12), (32, 40, 14)]:
        d.ellipse([x - r, y - r, x + r, y + r], fill=C("K"))
        d.ellipse([x - r + 1, y - r + 1, x + r - 1, y + r - 1], fill=C("sakura"))
    for _ in range(30):
        x, y = rng.randint(14, 50), rng.randint(10, 48)
        d.point((x, y), fill=C("sakurad"))
    d.ellipse([26, 16, 36, 26], fill=C("snow"))
    return img


def stone_path():
    """64x64 stone path tile (seamless-ish)."""
    img = new(64, 64)
    d = ImageDraw.Draw(img)
    import random
    rng = random.Random(31)
    d.rectangle([0, 0, 63, 63], fill=C("stoned"))
    for _ in range(10):
        x, y = rng.randint(2, 54), rng.randint(2, 54)
        w, h = rng.randint(8, 16), rng.randint(6, 12)
        d.rounded_rectangle([x, y, x + w, y + h], radius=3, fill=C("K"))
        d.rounded_rectangle([x + 1, y + 1, x + w - 1, y + h - 1], radius=2, fill=C("stone"))
    return img


def plaza_tile():
    """64x64 plaza tile with star motif."""
    img = new(64, 64)
    d = ImageDraw.Draw(img)
    d.rectangle([0, 0, 63, 63], fill=C("K"))
    d.rectangle([2, 2, 61, 61], fill=C("plas"))
    d.rectangle([2, 2, 61, 8], fill=C("plasd"))
    _star(d, 32, 36, 10, "roof")
    _star(d, 32, 36, 6, "plas")
    return img


BUILDINGS = {
    "house_a": (house_a, "assets/town/house_a.png"),
    "house_b": (house_b, "assets/town/house_b.png"),
    "station_hall": (station_hall, "assets/town/station_hall.png"),
    "clock_tower": (clock_tower, "assets/town/clock_tower.png"),
    "platform": (platform, "assets/town/platform.png"),
    "stall": (stall, "assets/town/stall.png"),
    "bulletin": (bulletin, "assets/town/bulletin.png"),
    "vending": (vending, "assets/town/vending.png"),
    "torii": (torii, "assets/town/torii.png"),
    "shrine_hall": (shrine_hall, "assets/town/shrine_hall.png"),
    "stone_lantern": (stone_lantern, "assets/town/stone_lantern.png"),
    "lake": (lake, "assets/town/lake.png"),
    "bridge": (bridge, "assets/town/bridge.png"),
    "dock": (dock, "assets/town/dock.png"),
    "town_gate": (town_gate, "assets/town/town_gate.png"),
    "power_pole": (power_pole, "assets/town/power_pole.png"),
    "sakura_tree": (sakura_tree, "assets/town/sakura_tree.png"),
    "stone_path": (stone_path, "assets/town/stone_path.png"),
    "plaza_tile": (plaza_tile, "assets/town/plaza_tile.png"),
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    os.makedirs(args.out, exist_ok=True)
    manifest = []
    for name, (fn, rel) in BUILDINGS.items():
        img = fn()
        img.save(os.path.join(args.out, name + ".png"))
        manifest.append({"path": rel, "width": img.size[0], "height": img.size[1]})
    with open(os.path.join(args.out, "town_manifest.json"), "w") as fh:
        json.dump(manifest, fh, indent=1)
    print("generated %d town sprites -> %s" % (len(manifest), args.out))


if __name__ == "__main__":
    main()
