#!/usr/bin/env python3
"""Generate original CC0 hero + pet + NPC art for Paloria (AT-D, refreshed).

Anime-chibi pixel art drawn with PIL at 16x16 per frame.

Contracts (unchanged, enforced by tools/validate_hero_art.py):
  hero_sheet.png: 64x112 (4 cols x 7 rows)
    cols: down / up / left / right
    rows: walk 0-3, attack windup 4, attack strike 5, roll 6
    walk rows: col 2 (left) must alpha-mirror col 3 (right)
  palfox_sheet.png: 64x64 (4 cols x 4 rows)
    rows: down / up / left / right ; cols: idle + 3 walk frames
  npc_<variant>.png: 64x64 (4 cols x 4 rows), same layout as palfox

Palette: every opaque pixel must be in the validator set (base + HERO_EXTRA +
FOX_EXTRA). No anti-aliasing.

Provenance: GENERATED by project tool, CC0-1.0, "Paloria project".
"""
import argparse
import os

from PIL import Image, ImageDraw

PAL = {
    # outline / neutrals
    "K":      (29, 36, 51),    # 1D2433
    "white":  (247, 235, 210), # F7EBD2 (in both validators)
    "cream":  (240, 230, 210), # F0E6D2 (strict validator set)
    "grey":   (138, 148, 166), # 8A94A6 (strict validator set)
    "char":   (58, 67, 86),    # 3A4356 (strict validator set)
    # hero
    "hair":   (46, 58, 92),    # 2E3A5C
    "hairl":  (74, 95, 138),   # 4A5F8A
    "skin":   (242, 200, 155), # F2C89B
    "skind":  (210, 160, 120), # D2A078
    "blush":  (214, 64, 94),   # D6405E
    "jacket": (63, 95, 138),   # 3F5F8A
    "jacketd": (44, 68, 99),   # 2C4463
    "scarf":  (240, 230, 210), # F0E6D2
    "scarfd": (217, 201, 168), # D9C9A8
    "gold":   (242, 194, 48),  # F2C230
    "strap":  (169, 116, 79),   # A9744F (strict validator set)
    "pouch":  (169, 116, 79),  # A9744F
    "pants":  (59, 59, 74),    # 3B3B4A
    "boots":  (107, 74, 46),   # 6B4A2E
    "glow":   (255, 179, 71),  # FFB347
    "red":    (192, 57, 43),   # C0392B
    "orange": (242, 129, 46),  # F2812E
    "green":  (79, 174, 79),   # 4FAE4F
    "sky":    (63, 167, 214),  # 3FA7D6
    # palfox
    "fox":    (232, 150, 80),  # E89650
    "foxd":   (190, 110, 55),  # BE6E37
    "foxc":   (247, 235, 210), # F7EBD2
}


def C(n):
    return PAL[n] + (255,)


def new_frame():
    return Image.new("RGBA", (16, 16), (0, 0, 0, 0))


def px(d, x, y, c):
    if 0 <= x < 16 and 0 <= y < 16:
        d.point((x, y), fill=C(c))


def pxc(d, x, y, rgba):
    """Plot a raw RGBA tuple (for NPC custom palettes)."""
    if 0 <= x < 16 and 0 <= y < 16:
        d.point((x, y), fill=rgba)


def rect(d, x0, y0, x1, y1, c):
    d.rectangle([max(0, x0), max(0, y0), min(15, x1), min(15, y1)], fill=C(c))


def limb(d, x0, y0, x1, y1, c, w=2):
    """Thick anti-aliased-free limb segment with rounded ends."""
    d.line([(x0, y0), (x1, y1)], fill=C("K"), width=w + 2)
    d.line([(x0, y0), (x1, y1)], fill=C(c), width=w)


# ------------------------------------------------------------------ hero
# Frame anatomy (facing down), 16x16:
#   rows 0-2: hair mass + ahoge        rows 3-6: face
#   row 7: neck + scarf knot           row 8: scarf band
#   rows 9-11: jacket torso            row 12: belt
#   rows 13-14: legs                   row 15: boots
HAIR = "hair"
HAIRL = "hairl"


def _hair_back(d, facing, bob):
    # big hair mass behind/around head
    if facing == "up":
        rect(d, 3, 1 + bob, 12, 8 + bob, HAIR)
        rect(d, 4, 2 + bob, 11, 7 + bob, HAIRL)
        for x in range(3, 13, 2):
            px(d, x, 8 + bob, HAIR)  # hair tips
        px(d, 5, 3 + bob, "white")
        px(d, 6, 3 + bob, "white")
    else:
        rect(d, 4, 1 + bob, 11, 4 + bob, HAIR)
        rect(d, 3, 2 + bob, 4, 7 + bob, HAIR)   # side locks
        rect(d, 11, 2 + bob, 12, 7 + bob, HAIR)
        px(d, 5, 1 + bob, HAIRL)
        px(d, 8, 1 + bob, HAIRL)


def _face(d, facing, bob):
    if facing == "up":
        return  # hair covers (drawn in _hair_back)
    rect(d, 4, 3 + bob, 11, 7 + bob, "skin")
    if facing == "down":
        # bangs with spikes
        for x in range(4, 12):
            px(d, x, 3 + bob, HAIR)
        for x in (5, 7, 9):
            px(d, x, 4 + bob, HAIR)
        px(d, 5, 2 + bob, HAIRL)
        # eyes with sparkle
        for ex in (6, 9):
            px(d, ex, 5 + bob, "K")
        px(d, 6, 5 + bob, "white")
        # blush + mouth
        px(d, 5, 6 + bob, "blush")
        px(d, 10, 6 + bob, "blush")
        px(d, 7, 6 + bob, "skind")
        px(d, 8, 6 + bob, "skind")
    else:  # side
        for x in range(4, 12):
            px(d, x, 3 + bob, HAIR)
        px(d, 7, 4 + bob, HAIR)
        ex = 6 if facing == "left" else 9
        px(d, ex, 5 + bob, "K")
        px(d, ex, 4 + bob, "white")
        bx = 5 if facing == "left" else 10
        px(d, bx, 6 + bob, "blush")
    # ahoge
    d.line([(8, 1 + bob), (10, -1 + bob)], fill=C(HAIR), width=1)


def _torso(d, facing, bob, arm_l=(0, 0), arm_r=(0, 0), crouch=0):
    y = bob + crouch
    # scarf band + knot + tail
    rect(d, 4, 7 + y, 11, 8 + y, "scarf")
    rect(d, 4, 7 + y, 5, 8 + y, "scarfd")
    px(d, 8, 8 + y, "gold")  # star pin on scarf
    # jacket torso
    rect(d, 4, 9 + y, 11, 12 + y, "jacket")
    rect(d, 4, 9 + y, 5, 12 + y, "jacketd")
    d.line([(8, 9 + y), (8, 12 + y)], fill=C("jacketd"))  # zipper
    for by in (10, 11):
        px(d, 8, by + y, "K")
    # satchel strap (diagonal) + pouch at hip
    d.line([(4, 9 + y), (11, 12 + y)], fill=C("strap"), width=1)
    if facing in ("down", "left"):
        px_, py_ = (11, 12 + y) if facing == "down" else (3, 12 + y)
    else:
        px_, py_ = (4, 12 + y) if facing == "up" else (12, 12 + y)
    rect(d, px_ - 1, py_ - 1, px_ + 1, py_ + 1, "pouch")
    d.point((px_, py_), fill=C("strap"))
    # arms
    lx, ly = 3 + arm_l[0], 9 + y + arm_l[1]
    rx, ry = 12 + arm_r[0], 9 + y + arm_r[1]
    limb(d, 3, 9 + y, lx, ly + 2, "jacket")
    limb(d, 12, 9 + y, rx, ry + 2, "jacket")
    px(d, lx, ly + 3, "skin")  # hands
    px(d, rx, ry + 3, "skin")
    # belt
    rect(d, 4, 12 + y, 11, 12 + y, "pants")
    px(d, 7, 12 + y, "gold")
    px(d, 8, 12 + y, "gold")


def _legs(d, bob, step_l, step_r, crouch=0):
    y = bob + crouch
    for lx, off in ((5, step_l), (10, step_r)):
        limb(d, lx, 12 + y, lx + off, 14 + y, "pants")
        rect(d, lx + off - 1, 14 + y, lx + off + 1, 15 + y, "boots")


def draw_hero(facing, pose):
    """pose: ('walk', step) | ('windup',) | ('strike',) | ('roll',)."""
    img = new_frame()
    d = ImageDraw.Draw(img)
    if pose[0] == "roll":
        # tucked spinning ball + motion arcs
        d.ellipse([2, 5, 13, 15], fill=C("K"))
        d.ellipse([3, 6, 12, 14], fill=C("jacket"))
        d.ellipse([4, 4, 10, 9], fill=C("K"))
        d.ellipse([5, 5, 9, 8], fill=C(HAIR))
        px(d, 6, 6, HAIRL)
        d.arc([1, 4, 14, 15], 200, 340, fill=C("scarf"))
        px(d, 3, 11, "scarf")
        px(d, 12, 11, "scarf")
        px(d, 2, 8, "white")
        px(d, 13, 7, "white")
        return img

    bob = 0
    if pose[0] == "walk":
        bob = 0 if pose[1] % 2 == 0 else -1

    if pose[0] == "windup":
        # crouch, sword arm pulled up-back
        _legs(d, 0, 1, -1, crouch=1)
        _torso(d, facing, 0, arm_l=(0, 1), arm_r=(2, -4), crouch=1)
        # sword raised: blade up from right hand
        hx, hy = (14, 6) if facing != "left" else (1, 6)
        limb(d, 12, 9, hx, hy, "skin", w=1)
        d.line([(hx, hy), (hx + (1 if facing != "left" else -1), hy - 6)],
               fill=C("K"), width=3)
        d.line([(hx, hy), (hx + (1 if facing != "left" else -1), hy - 6)],
               fill=C("white"), width=1)
        px(d, hx, hy, "gold")  # guard
    elif pose[0] == "strike":
        # lunge + sword extended toward facing + swoosh
        dv = {"down": (0, 1), "up": (0, -1), "left": (-1, 0),
              "right": (1, 0)}[facing]
        dx, dy = dv[0], dv[1]
        _legs(d, 0, 2 * dx + (1 if dx == 0 else 0),
              -1 * dx + (1 if dx == 0 else 0))
        _torso(d, facing, 0, arm_l=(dx * 2, dy * 2), arm_r=(dx * 2, dy * 2))
        sx, sy = 8 + dx * 3, 10 + dy * 3
        ex, ey = 8 + dx * 8, 10 + dy * 8
        d.line([(sx, sy), (ex, ey)], fill=C("K"), width=3)
        d.line([(sx, sy), (ex, ey)], fill=C("white"), width=1)
        px(d, sx, sy, "gold")
        # swoosh arc
        for t in range(5):
            a = t / 4
            wx = int(8 + dx * 6 + (-dy) * (a - 0.5) * 8)
            wy = int(10 + dy * 6 + (dx) * (a - 0.5) * 8)
            px(d, wx, wy, "white")
            px(d, wx + 1, wy, "sky")
    else:  # walk
        step = pose[1]
        offs = [(0, 0), (-1, 1), (0, 0), (1, -1)][step]
        sw = [0, 1, 0, -1][step]  # arm swing
        _legs(d, bob, offs[0], offs[1])
        _torso(d, facing, bob, arm_l=(-sw, 0), arm_r=(sw, 0))

    _hair_back(d, facing, bob if pose[0] == "walk" else 0)
    _face(d, facing, bob if pose[0] == "walk" else 0)
    return img


def hero_sheet():
    sheet = Image.new("RGBA", (64, 112), (0, 0, 0, 0))
    rows = [("walk", 0), ("walk", 1), ("walk", 2), ("walk", 3),
            ("windup",), ("strike",), ("roll",)]
    for r, pose in enumerate(rows):
        # draw down/up/left, mirror left -> right for side views
        sheet.paste(draw_hero("down", pose), (0 * 16, r * 16))
        sheet.paste(draw_hero("up", pose), (1 * 16, r * 16))
        left = draw_hero("left", pose)
        sheet.paste(left, (2 * 16, r * 16))
        sheet.paste(left.transpose(Image.FLIP_LEFT_RIGHT), (3 * 16, r * 16))
    return sheet

# ------------------------------------------------------------------ palfox
def draw_palfox(facing, step):
    """Fluffy fox pet. step 0 = idle, 1-3 = walk."""
    img = new_frame()
    d = ImageDraw.Draw(img)
    walking = step != 0
    hop = 0 if step % 2 == 0 else -1
    wag = [0, 1, 0, -1][step]
    # big fluffy tail (behind body; side depends on facing)
    tx = {"down": 12, "up": 3, "left": 12, "right": 3}[facing] + wag
    ty = 9 + hop
    d.ellipse([tx - 4, ty - 4, tx + 4, ty + 4], fill=C("K"))
    d.ellipse([tx - 3, ty - 3, tx + 3, ty + 3], fill=C("fox"))
    d.ellipse([tx - 2, ty - 2, tx + 2, ty + 2], fill=C("foxd"))
    tipx = tx + (3 if tx > 8 else -3)
    d.ellipse([tipx - 2, ty - 2, tipx + 2, ty + 2], fill=C("foxc"))
    # body (fluffy, cream belly)
    d.ellipse([3, 7 + hop, 12, 14 + hop], fill=C("K"))
    d.ellipse([4, 8 + hop, 11, 13 + hop], fill=C("fox"))
    d.ellipse([5, 10 + hop, 10, 13 + hop], fill=C("foxc"))
    # fur scallops on back
    for fx in (5, 7, 9):
        d.arc([fx - 2, 6 + hop, fx + 2, 10 + hop], 180, 360, fill=C("foxd"))
    # head
    d.ellipse([3, 2 + hop, 12, 9 + hop], fill=C("K"))
    d.ellipse([4, 3 + hop, 11, 8 + hop], fill=C("fox"))
    # ear tufts with cream inner
    for ex in (4, 10):
        d.polygon([(ex, 4 + hop), (ex + 2, 4 + hop), (ex + 1, 0 + hop)], fill=C("K"))
        d.polygon([(ex, 3 + hop), (ex + 2, 3 + hop), (ex + 1, 1 + hop)], fill=C("foxd"))
        px(d, ex + 1, 2 + hop, "foxc")
    # cheek fluff
    for cx_ in (3, 12):
        d.ellipse([cx_ - 2, 5 + hop, cx_ + 1, 8 + hop], fill=C("foxc"),
                  outline=C("K"))
    # face
    if facing == "down":
        for ex in (6, 9):
            px(d, ex, 5 + hop, "K")
        px(d, 6, 4 + hop, "white")
        px(d, 7, 6 + hop, "K")  # nose
        px(d, 8, 7 + hop, "K")  # mouth
        px(d, 5, 6 + hop, "blush")
        px(d, 10, 6 + hop, "blush")
    elif facing == "up":
        rect(d, 4, 3 + hop, 11, 6 + hop, "foxd")  # back of head fluff
        for fx in (5, 8):
            d.arc([fx - 2, 2 + hop, fx + 2, 6 + hop], 180, 360, fill=C("fox"))
    else:
        ex = 6 if facing == "left" else 9
        px(d, ex, 5 + hop, "K")
        px(d, ex, 4 + hop, "white")
        px(d, ex + (1 if facing == "right" else -1), 6 + hop, "K")
    # legs with walk offsets
    lo = [0, -1, 0, 1][step]
    for i, lx in enumerate((5, 10)):
        off = lo if i == 0 else -lo
        limb(d, lx, 12 + hop, lx + off, 14 + hop, "foxd")
    return img


def palfox_sheet():
    sheet = Image.new("RGBA", (64, 64), (0, 0, 0, 0))
    for r, facing in enumerate(["down", "up", "left", "right"]):
        for c in range(4):
            sheet.paste(draw_palfox(facing, c), (c * 16, r * 16))
    # mirror left row -> right row for consistency
    for c in range(4):
        left = sheet.crop((c * 16, 2 * 16, c * 16 + 16, 3 * 16))
        sheet.paste(left.transpose(Image.FLIP_LEFT_RIGHT), (c * 16, 3 * 16))
    return sheet


# ------------------------------------------------------------------ npcs
NPC_DEFS = {
    "elder": {
        "hair": (200, 200, 210), "top": (44, 68, 99), "topd": (29, 36, 51),
        "skin": (242, 200, 155), "beard": (240, 230, 210), "acc": "pouch",
        "hat": None,
    },
    "merchant": {
        "hair": (169, 116, 79), "top": (240, 230, 210), "topd": (217, 201, 168),
        "skin": (242, 200, 155), "apron": (242, 129, 46), "acc": "pouch",
        "hat": "headband",
    },
    "kid": {
        "hair": (59, 59, 74), "top": (242, 194, 48), "topd": (201, 111, 46),
        "skin": (245, 210, 170), "acc": "pouch",
        "hat": "cap",
    },
}


def _rgb(t):
    return t + (255,)


def draw_npc(variant, facing, step):
    P = NPC_DEFS[variant]
    img = new_frame()
    d = ImageDraw.Draw(img)
    hop = 0 if step % 2 == 0 else -1
    small = variant == "kid"
    # body robe/shirt
    bw = 7 if small else 8
    x0 = 8 - bw // 2
    d.ellipse([x0, 6 + hop, x0 + bw, 13 + hop], fill=C("K"))
    d.ellipse([x0 + 1, 7 + hop, x0 + bw - 1, 12 + hop], fill=_rgb(P["top"]))
    d.line([(x0 + 1, 7 + hop), (x0 + 1, 12 + hop)], fill=_rgb(P["topd"]))
    if variant == "merchant":  # apron
        d.rectangle([x0 + 2, 8 + hop, x0 + bw - 2, 12 + hop], fill=_rgb(P["apron"]))
        d.line([(8, 8 + hop), (8, 12 + hop)], fill=C("K"))
    if variant == "elder":  # obi belt
        d.rectangle([x0 + 1, 10 + hop, x0 + bw - 1, 11 + hop], fill=C("pants"))
    # head
    hw = 7 if small else 8
    hx0 = 8 - hw // 2
    d.rectangle([hx0, 1 + hop, hx0 + hw - 1, 6 + hop], fill=C("K"))
    d.rectangle([hx0 + 1, 2 + hop, hx0 + hw - 2, 5 + hop], fill=_rgb(P["skin"]))
    # hair / hat
    if P["hat"] == "cap":
        d.rectangle([hx0 - 1, 0 + hop, hx0 + hw, 2 + hop], fill=C("red"))
        d.rectangle([hx0 + hw - 1, 1 + hop, hx0 + hw + 1, 2 + hop], fill=C("red"))
        px(d, hx0 + hw // 2, 0 + hop, "gold")
    elif P["hat"] == "headband":
        for x in range(hx0, hx0 + hw):
            pxc(d, x, 1 + hop, _rgb(P["hair"]))
        d.rectangle([hx0, 2 + hop, hx0 + hw - 1, 3 + hop], fill=C("green"))
        d.line([(hx0 + hw - 1, 2 + hop), (hx0 + hw + 1, 4 + hop)], fill=C("green"))
    else:
        for x in range(hx0, hx0 + hw):
            pxc(d, x, 1 + hop, _rgb(P["hair"]))
        d.rectangle([hx0, 2 + hop, hx0 + hw - 1, 2 + hop], fill=_rgb(P["hair"]))
        if variant == "elder":  # topknot
            d.ellipse([hx0 + hw // 2 - 1, -1 + hop, hx0 + hw // 2 + 1, 2 + hop],
                      fill=_rgb(P["hair"]), outline=C("K"))
    if variant == "elder" and facing == "down":
        # long beard
        d.polygon([(hx0 + 2, 6 + hop), (hx0 + hw - 3, 6 + hop),
                   (8, 11 + hop)], fill=_rgb(P["beard"]), outline=C("K"))
    # face
    if facing == "down":
        px(d, hx0 + 2, 4 + hop, "K")
        px(d, hx0 + hw - 3, 4 + hop, "K")
        if variant == "kid":
            px(d, hx0 + 2, 5 + hop, "blush")
            px(d, hx0 + hw - 3, 5 + hop, "blush")
    elif facing in ("left", "right"):
        ex = hx0 + 2 if facing == "left" else hx0 + hw - 3
        px(d, ex, 4 + hop, "K")
    # accessories: elder staff / merchant basket / kid star pin
    if variant == "elder":
        sx = x0 + bw + 1
        d.line([(sx, 5 + hop), (sx, 14 + hop)], fill=C("pouch"), width=2)
        d.line([(sx, 5 + hop), (sx, 14 + hop)], fill=C("K"), width=1) if False else None
        d.ellipse([sx - 2, 3 + hop, sx + 2, 7 + hop], fill=C("gold"), outline=C("K"))
    elif variant == "merchant":
        bx = x0 - 2
        d.rectangle([bx - 1, 9 + hop, bx + 2, 12 + hop], fill=C("pouch"),
                    outline=C("K"))
        d.arc([bx - 1, 7 + hop, bx + 2, 10 + hop], 180, 360, fill=C("strap"))
    else:
        px(d, 8, 9 + hop, "gold")
    # legs
    lo = [0, -1, 0, 1][step]
    for i, lx in enumerate((6, 9)):
        off = lo if i == 0 else -lo
        if variant == "elder":
            d.line([(lx, 12 + hop), (lx + off, 14 + hop)], fill=C("K"), width=4)
            d.line([(lx, 12 + hop), (lx + off, 14 + hop)], fill=_rgb(P["top"]),
                   width=2)
        else:
            limb(d, lx, 12 + hop, lx + off, 14 + hop, "pants")
    return img


def npc_sheet(variant):
    sheet = Image.new("RGBA", (64, 64), (0, 0, 0, 0))
    for r, facing in enumerate(["down", "up", "left", "right"]):
        for c in range(4):
            if facing == "right":
                left = draw_npc(variant, "left", c)
                sheet.paste(left.transpose(Image.FLIP_LEFT_RIGHT), (c * 16, r * 16))
            else:
                sheet.paste(draw_npc(variant, facing, c), (c * 16, r * 16))
    return sheet


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    os.makedirs(args.out, exist_ok=True)
    hero_sheet().save(os.path.join(args.out, "hero_sheet.png"))
    palfox_sheet().save(os.path.join(args.out, "palfox_sheet.png"))
    for variant in ("elder", "merchant", "kid"):
        npc_sheet(variant).save(os.path.join(args.out, "npc_%s.png" % variant))
    print("generated hero + palfox + npc sheets ->", args.out)


if __name__ == "__main__":
    main()
