param(
    [string]$ProjectPath = (Split-Path -Parent $PSScriptRoot),
    [string]$AssetDocsPath = (Join-Path (Split-Path -Parent $PSScriptRoot) 'docs\assets')
)

$ErrorActionPreference = 'Stop'
$manifestPath = Join-Path $AssetDocsPath 'asset_manifest.csv'
$overridePath = Join-Path $AssetDocsPath 'asset_action_overrides.csv'
$outputPath = Join-Path $AssetDocsPath 'asset_actions.csv'
$reportPath = Join-Path $AssetDocsPath 'REPLACEMENT_PLAN.md'
if (-not (Test-Path -LiteralPath $manifestPath -PathType Leaf)) {
    throw "Asset manifest not found: $manifestPath"
}

$overrides = @{}
if (Test-Path -LiteralPath $overridePath -PathType Leaf) {
    foreach ($entry in (Import-Csv -LiteralPath $overridePath)) {
        if ($entry.path) { $overrides[$entry.path.Replace('\', '/')] = $entry }
    }
}

function Get-Owner([string]$Category) {
    switch ($Category) {
        { $_ -in @('music', 'sfx') } { return 'audio' }
        { $_ -in @('hunter', 'monsters') } { return 'character-art' }
        'tilesets' { return 'environment-art' }
        { $_ -in @('items', 'buildings') } { return 'gameplay-art' }
        'fx' { return 'vfx' }
        default { return 'art-tech-debt' }
    }
}

$manifest = @(Import-Csv -LiteralPath $manifestPath | Sort-Object path)
$actions = @(foreach ($asset in $manifest) {
    $override = if ($overrides.ContainsKey($asset.path)) { $overrides[$asset.path] } else { $null }
    $isReferenced = [System.Convert]::ToBoolean($asset.referenced)
    $leafName = [System.IO.Path]::GetFileNameWithoutExtension($asset.path)
    $isScratch = $leafName -match '^(test_|preview_|row_\d+$)|(_check$)'

    if ($isReferenced) {
        $defaultAction = 'VERIFY_OR_REPLACE'
        $defaultPriority = 'P0'
        $defaultRationale = 'Runtime dependency with unknown provenance; verify source/license or replace before distribution.'
    } elseif ($isScratch) {
        $defaultAction = 'REMOVE_AFTER_REFERENCE_AUDIT'
        $defaultPriority = 'P3'
        $defaultRationale = 'Unreferenced preview/test/intermediate file; remove only after snapshot and visual/reference audit.'
    } elseif ($asset.duplicate_group) {
        $defaultAction = 'DEDUP_AFTER_REFERENCE_AUDIT'
        $defaultPriority = 'P2'
        $defaultRationale = 'Unreferenced byte-identical duplicate; retain until canonical path and external references are reviewed.'
    } else {
        $defaultAction = 'HOLD_FOR_REVIEW'
        $defaultPriority = 'P2'
        $defaultRationale = 'Unreferenced content with unknown provenance; decide future use before removal or replacement.'
    }

    [PSCustomObject][ordered]@{
        path = $asset.path
        referenced = $asset.referenced
        provenance_status = $asset.provenance_status
        action = if ($override -and $override.action) { $override.action } else { $defaultAction }
        priority = if ($override -and $override.priority) { $override.priority } else { $defaultPriority }
        owner = if ($override -and $override.owner) { $override.owner } else { Get-Owner $asset.category }
        replacement_target = if ($override -and $override.replacement_target) { $override.replacement_target } elseif ($isReferenced) { "assets/game/$($asset.category)/" } else { '' }
        rationale = if ($override -and $override.rationale) { $override.rationale } else { $defaultRationale }
    }
})

$actions | Export-Csv -LiteralPath $outputPath -NoTypeInformation -Encoding UTF8
$actionGroups = $actions | Group-Object action | Sort-Object Name
$priorityGroups = $actions | Group-Object priority | Sort-Object Name
$runtimeByOwner = $actions | Where-Object { $_.referenced -eq 'True' } | Group-Object owner | Sort-Object Name

$lines = @(
    '# Asset quarantine and replacement plan',
    '',
    '> Generated by `tools/generate_asset_triage.ps1` from the asset manifest plus curated `asset_action_overrides.csv`.',
    '',
    "Generated: $((Get-Date).ToString('yyyy-MM-dd'))",
    '',
    '## Gate status',
    '',
    "- Assets classified: $($actions.Count)/$($manifest.Count)",
    "- Runtime P0 assets: $(@($actions | Where-Object { $_.priority -eq 'P0' }).Count)",
    '- Files moved/deleted/relicensed: 0',
    '',
    'Every current runtime asset is `VERIFY_OR_REPLACE/P0` until provenance is verified. Priority describes release risk, not permission to replace files without visual review and a tested migration.',
    '',
    '## By action',
    '',
    '| Action | Files | Meaning |',
    '|---|---:|---|'
)
$meanings = @{
    'VERIFY_OR_REPLACE' = 'Verify author/source/license; otherwise create or admit a replacement.'
    'HOLD_FOR_REVIEW' = 'Potential future content; decide use before removal.'
    'DEDUP_AFTER_REFERENCE_AUDIT' = 'Choose canonical copy only after reference audit.'
    'REMOVE_AFTER_REFERENCE_AUDIT' = 'Scratch/preview candidate; remove in a separate reversible package.'
}
foreach ($group in $actionGroups) {
    $lines += "| $($group.Name) | $($group.Count) | $($meanings[$group.Name]) |"
}

$lines += @('', '## By priority', '', '| Priority | Files |', '|---|---:|')
foreach ($group in $priorityGroups) { $lines += "| $($group.Name) | $($group.Count) |" }

$lines += @('', '## Runtime replacement ownership', '', '| Owner | P0 files | First deliverable |', '|---|---:|---|')
$deliverables = @{
    'audio' = 'License audit current music/SFX; define semantic audio event map.'
    'character-art' = 'Original player + one pet animation slice and source recipe.'
    'environment-art' = 'Starter biome tile/prop set on the 32 px target grid.'
    'gameplay-art' = 'Core item/building icons aligned with UI and world silhouettes.'
    'vfx' = 'Original hit/capture/work VFX with timing and accessibility variants.'
    'art-tech-debt' = 'Move root scratch files only in a later cleanup package.'
}
foreach ($group in $runtimeByOwner) {
    $lines += "| $($group.Name) | $($group.Count) | $($deliverables[$group.Name]) |"
}

$lines += @(
    '',
    '## Execution order',
    '',
    '1. Resolve P0 player, pet, starter biome, HUD item/building and core audio assets needed by one vertical slice.',
    '2. Admit verified package/original source into immutable `assets/vendor`; generate derivatives under `assets/game`.',
    '3. Update one scene/data definition at a time; run Godot gate and visual review.',
    '4. Keep old runtime asset until every reference is migrated and the replacement is approved.',
    '5. Handle P2/P3 dedup/removal in a separate commit after reference search and restore test.',
    '',
    '## Curated overrides',
    '',
    'Edit `asset_action_overrides.csv` when a human/agent review changes action, priority, owner, target or rationale. Regenerate this report; do not edit `asset_actions.csv` directly.'
)
$lines | Set-Content -LiteralPath $reportPath -Encoding UTF8

Write-Host "Asset triage generated: $($actions.Count) assets, $(@($actions | Where-Object { $_.priority -eq 'P0' }).Count) runtime P0."
