#!/usr/bin/env python3
"""Generate original CC0 placeholder art for Paloria 2D (U4.2).

Every sprite is drawn by this script from the Paloria-16 palette defined in
docs/assets/ART_BIBLE.md. Provenance: GENERATED by project tool, license
CC0-1.0, author "Paloria project". Nothing here copies third-party pixels.

Usage:
    python3 tools/generate_placeholders.py --out /tmp/paloria_gen
Writes PNGs plus generation_manifest.json describing every file.
"""
import argparse
import json
import os
import sys

from PIL import Image, ImageDraw

PALETTE = {
    "K": (29, 36, 51),      # outline
    "k": (58, 67, 86),      # ink_soft
    "S": (242, 201, 155),   # skin
    "s": (214, 158, 109),   # skin_shade
    "L": (79, 174, 79),     # leaf
    "l": (47, 125, 58),     # leaf_dark
    "W": (169, 116, 79),    # wood
    "w": (122, 82, 51),     # wood_dark
    "T": (154, 163, 178),   # stone
    "t": (107, 114, 128),   # stone_dark
    "A": (63, 167, 214),    # water
    "a": (36, 116, 163),    # water_dark
    "F": (242, 129, 46),    # fire
    "G": (242, 194, 48),    # gold
    "R": (214, 64, 94),     # berry
    "B": (79, 111, 181),    # cloth
    "N": (238, 243, 248),   # snow
}

GENERATED = []  # (relative_path, width, height, kind)


def from_ascii(rows):
    h = len(rows)
    w = max(len(r) for r in rows)
    img = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    px = img.load()
    for y, row in enumerate(rows):
        for x, ch in enumerate(row):
            if ch == "." or ch == " ":
                continue
            if ch not in PALETTE:
                raise ValueError("unknown palette char %r" % ch)
            px[x, y] = PALETTE[ch] + (255,)
    return img


def save(img, rel_path):
    GENERATED.append((rel_path, img.size[0], img.size[1], "texture"))


# ---------------------------------------------------------------- items (16x16)
ITEMS = {
"beaf": [
"................",
"................",
"...KKKKK........",
"..KRRRRRK.......",
".KRRRRRRRK......",
".KRRkRRRRK......",
"KRRkRRRRRRK.....",
"KRRRRRRkRRK.....",
"KRRRRRRRRRK.....",
".KRRRkRRRK......",
".KRRRRRRRK......",
"..KRRRRRK.......",
"...KKKKK........",
"................",
"................",
"................",
],
"berry": [
"................",
"......l.........",
".....lL.........",
"....lLLl........",
"...KKKKK........",
"..KRRRRRK.......",
".KRNRRRRK.......",
".KRRRRRRK.......",
".KRRRRRRK.......",
"..KRRRRK........",
"...KKKK.........",
"................",
"................",
"................",
"................",
"................",
],
"bread": [
"................",
"................",
"................",
"....KKKKKK......",
"..KKWWWWWWKK....",
".KWWWWWWWWWWK...",
".KWwWWWWWWwWK...",
"KWWwWWWWWWwWWK..",
"KWWWWWWWWWWWWK..",
".KWwWWWWWWwWK...",
".KWWWWWWWWWWK...",
"..KKWWWWWWKK....",
"....KKKKKK......",
"................",
"................",
"................",
],
"cooked_meat": [
"................",
"................",
"...KKKK.........",
"..KWWWKK........",
".KWWWWWWK.......",
".KWkWWWWK.......",
"KWWkWWWWWK......",
"KWWWWWWkWK......",
"KWWWWkWWWK......",
".KWWWWWWK.......",
".KWkWWWWK.......",
"..KWWWWK........",
"...KKKK.........",
"....KK..........",
"....KWK.........",
"....KK..........",
],
"fertilizer": [
"................",
"......KK........",
".....KWWK.......",
".....KWWK.......",
"....KKWWKK......",
"....KWWWWK......",
"....KWWWWK......",
"...KKWWWWKK.....",
"...KWWWWWWK.....",
"...KWWWWWWK.....",
"...KWWWWWWK.....",
"...KKKKKKKK.....",
"................",
"................",
"................",
"................",
],
"giga_sphere": [
"................",
".....KKKK.......",
"...KKBBBBKK.....",
"..KBBBBBBBBK....",
".KBBNNBBBBBK....",
".KBBNBkBBBBK....",
"KBBBBBkBBBBBK...",
"KBBBBBkBBBBBK...",
"KBBBBBkBBBBBK...",
".KBBBBBBBBBK....",
".KBBBBkBBBBK....",
"..KBBBBBBBBK....",
"...KKBBBBKK.....",
".....KKKK.......",
"................",
"................",
],
"mega_sphere": [
"................",
".....KKKK.......",
"...KKRRRRKK.....",
"..KRRRRRRRRK....",
".KRRNNRRRRRK....",
".KRRNRkRRRRK....",
"KRRRRRkRRRRRK...",
"KRRRRRkRRRRRK...",
"KRRRRRkRRRRRK...",
".KRRRRRRRRRK....",
".KRRRRkRRRRK....",
"..KRRRRRRRRK....",
"...KKRRRRKK.....",
".....KKKK.......",
"................",
"................",
],
"hearty_stew": [
"................",
"................",
".....KKKKK......",
"....KFFFFFK.....",
"....KFAFAFK.....",
"...KKKKKKKKK....",
"..KTTTTTTTTTK...",
"..KTFFFFFFFTK...",
"..KTFRFRFRFTK...",
"..KTFFFFFFFTK...",
"..KTTTTTTTTTK...",
"..KKKKKKKKKKK...",
"................",
"................",
"................",
"................",
],
"iron_ingot": [
"................",
"................",
"................",
"................",
"................",
"....KKKKKKK.....",
"...KTTTTTTTK....",
"..KTTNTTTTTK....",
"..KTTTTTTTTK....",
"..KTTTTTTTTK....",
"...KTTTTTTK.....",
"....KKKKKKK.....",
"................",
"................",
"................",
"................",
],
"pal_elixir": [
"................",
"......KK........",
".....KRRK.......",
".....KRRK.......",
"....KKRRKK......",
"....KRRRRK......",
"...KRNRRRK......",
"...KRRRRRK......",
"...KRRkRRK......",
"...KRRRRRK......",
"....KRRRK.......",
"....KKKKK.......",
"................",
"................",
"................",
"................",
],
"pal_herb": [
"................",
".......lL.......",
"......lLLl......",
".....lLLLl......",
".....lLLl.......",
"..l..lLL...l....",
"..lL.lLl..lL....",
"...lLlLl.lLl....",
"....lLLl.lL.....",
".....lLl........",
"......K.........",
".....KWK........",
"................",
"................",
"................",
"................",
],
"pal_ingot": [
"................",
"................",
"................",
"................",
"................",
"....KKKKKKK.....",
"...KGGGGGGGK....",
"..KGGNGGGGGK....",
"..KGGGGGGGGK....",
"..KGGGGGGGGK....",
"...KGGGGGGK.....",
"....KKKKKKK.....",
"................",
"................",
"................",
"................",
],
"pal_ore": [
"................",
"................",
"................",
".....KKKK.......",
"...KKTTTTKK.....",
"..KTTTTTTTTK....",
".KTTtTTTTTTK....",
".KTTTTTGGTK.....",
"KTTTTTTGGGKT....",
"KTTtTTGGGGKT....",
"KTTTTTTGGGKT....",
".KTTTTTTTTK.....",
"..KTTTTTTK......",
"...KKKKKK.......",
"................",
"................",
],
"purified_water": [
"................",
"......KK........",
".....KAAK.......",
".....KAAK.......",
"....KKAAKK......",
"....KAAAAK......",
"...KANAAAK......",
"...KAAAAAK......",
"...KAAaAAK......",
"...KAAAAAK......",
"....KAAAK.......",
"....KKKKK.......",
"................",
"................",
"................",
"................",
],
"seed": [
"................",
"................",
"................",
"................",
".......l........",
"......lLl.......",
".....lLLl.......",
"......l.........",
".....KKK........",
"....KWWWK.......",
"....KWwWK.......",
"....KWWWK.......",
".....KKK........",
"................",
"................",
"................",
],
"stone": [
"................",
"................",
"................",
"................",
"....KKKK........",
"...KTTTTK.......",
"..KTTtTTK.......",
"..KTTTTTK.......",
"..KTTtTTK.......",
"...KTTTK........",
"....KKK.........",
"................",
"................",
"................",
"................",
"................",
],
"strawberry": [
"................",
".....lLl........",
"....lLLLl.......",
".....lLl........",
"...KKKKKK.......",
"..KRRRRRRK......",
".KRRNRRRRRK.....",
".KRRRRRRkRK.....",
".KRRRRRkRRK.....",
".KRRRkRRRRK.....",
"..KRRRRRRK......",
"...KRRRRK.......",
"....KRRK........",
".....KK.........",
"................",
"................",
],
"sword": [
"...............N",
"..............Nk",
".............Nk.",
"............Nk..",
"...........Nk...",
"..........Nk....",
".....K...Nk.....",
"....KGK.Nk......",
".....KGk........",
"......kGk.......",
".....k.Gk.......",
"....k..Gk.......",
"...k...Gk.......",
"..KK...Gk.......",
"..KWK..k........",
"..KKK...........",
],
"wheat_crop": [
"................",
"....G...G.......",
"....GG..GG......",
"....GG..GG..G...",
".....GG.GG.GG...",
".....GGGGG.GG...",
"......GGGGGG....",
".......GGG......",
".......GGG......",
"....l..GGG..l...",
"....lL.GGG.lL...",
".....lLGGG.l....",
"......lGGG......",
".......K........",
"................",
"................",
],
"wood": [
"................",
"................",
"................",
"...KKKKKKK......",
"..KWWWWWWWK.....",
"..KWkWWkWWK.....",
"..KWWWWWWWK.....",
"..KWkWWWWWK.....",
"..KWWWWkWWK.....",
"..KWWWWWWWK.....",
"...KKKKKKK......",
"................",
"................",
"................",
"................",
"................",
],
}

CROP_STAGES = [
[  # stage 0: tilled soil
"................",
"................",
"................",
"................",
"................",
"..KKKKKKKKKKKK..",
"..KwwwwwwwwwwK..",
"..KwWwWwWwWwWK..",
"..KwwwwwwwwwwK..",
"..KwWwWwWwWwWK..",
"..KwwwwwwwwwwK..",
"..KKKKKKKKKKKK..",
"................",
"................",
"................",
"................",
],
[  # stage 1: sprouts
"................",
"................",
"................",
"................",
"......l.........",
".....lLl...l....",
"..KKKKKKKKKKKK..",
"..KwwwwlLlwwwK..",
"..KwWwLlwwWwWK..",
"..KwwwwlwwwwK...",
"..KwWwWwWwWwWK..",
"..KwwwwwwwwwwK..",
"..KKKKKKKKKKKK..",
"................",
"................",
"................",
],
[  # stage 2: growing
"................",
"................",
".....lLl........",
"....lLLLl...l...",
"....lLlLl..lLl....",
".....lLl...lLl..",
"..KKKKKKKKKKKK..",
"..KwwlLLlwwwK...",
"..KwWlLLLlwwWK..",
"..KwwlLLlwwwK...",
"..KwWwlLlwWwWK..",
"..KwwwwwwwwwwK..",
"..KKKKKKKKKKKK..",
"................",
"................",
"................",
],
[  # stage 3: mature
"................",
"................",
"....GGGGG.......",
"...GGGGGGG..G...",
"...GGGGG.GG...",
"....GGGGG.GGGG..",
"..KGGGGGGGGGGK..",
"..KGGGGGGGGGGK..",
"..KGGGGGGGGGGK..",
"..KGGGGGGGGGGK..",
"..KGGGGGGGGGGK..",
"..KwwwwwwwwwwK..",
"..KKKKKKKKKKKK..",
"................",
"................",
"................",
],
]

# ------------------------------------------------------- buildings (PIL drawn)
def _pal(name):
    return PALETTE[name] + (255,)


def _outlined_rect(d, x0, y0, x1, y1, fill, outline="K"):
    d.rectangle([x0, y0, x1, y1], fill=_pal(outline))
    d.rectangle([x0 + 1, y0 + 1, x1 - 1, y1 - 1], fill=_pal(fill))


def building_chest_wood():
    img = Image.new("RGBA", (32, 32), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    _outlined_rect(d, 4, 10, 27, 26, "W")          # body
    _outlined_rect(d, 4, 10, 27, 16, "w")          # lid
    d.rectangle([4, 16, 27, 18], fill=_pal("K"))   # lid seam
    d.rectangle([6, 12, 25, 14], fill=_pal("W"))   # lid highlight
    _outlined_rect(d, 13, 15, 18, 22, "G")         # latch
    d.rectangle([6, 20, 8, 24], fill=_pal("w"))    # side bands
    d.rectangle([23, 20, 25, 24], fill=_pal("w"))
    return img


def building_cooking_pot():
    img = Image.new("RGBA", (32, 32), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    # fire
    for i, (x, h) in enumerate([(9, 6), (13, 9), (17, 7), (21, 5)]):
        d.polygon([(x, 30), (x + 3, 30), (x + 1, 30 - h)], fill=_pal("F"))
    d.polygon([(13, 30), (16, 30), (14, 24)], fill=_pal("G"))
    # pot body
    d.ellipse([7, 12, 24, 28], fill=_pal("K"))
    d.ellipse([8, 13, 23, 27], fill=_pal("k"))
    d.ellipse([8, 13, 23, 20], fill=_pal("t"))
    d.ellipse([10, 14, 21, 19], fill=_pal("G"))     # stew surface
    d.rectangle([6, 11, 25, 14], fill=_pal("K"))   # rim
    d.rectangle([7, 12, 24, 13], fill=_pal("t"))
    # legs
    d.rectangle([9, 27, 11, 30], fill=_pal("K"))
    d.rectangle([20, 27, 22, 30], fill=_pal("K"))
    return img


def building_furnace_stove():
    img = Image.new("RGBA", (32, 32), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    _outlined_rect(d, 6, 6, 25, 28, "T")            # stone body
    d.rectangle([8, 8, 23, 10], fill=_pal("t"))     # top shade
    for x in (9, 14, 19):
        d.rectangle([x, 12, x + 2, 26], fill=_pal("t"))  # stone seams
    _outlined_rect(d, 10, 16, 21, 26, "K")          # fire mouth
    d.rectangle([11, 17, 20, 25], fill=_pal("F"))
    d.rectangle([13, 19, 18, 25], fill=_pal("G"))
    _outlined_rect(d, 11, 2, 20, 6, "t")            # chimney
    return img


def building_anvil():
    img = Image.new("RGBA", (32, 32), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    d.polygon([(4, 10), (28, 10), (24, 15), (8, 15)], fill=_pal("K"))
    d.polygon([(6, 11), (26, 11), (23, 14), (9, 14)], fill=_pal("T"))
    d.polygon([(8, 11), (14, 11), (12, 14), (9, 14)], fill=_pal("N"))
    d.rectangle([13, 15, 18, 22], fill=_pal("K"))   # waist
    d.rectangle([14, 16, 17, 21], fill=_pal("t"))
    d.polygon([(8, 22), (23, 22), (25, 28), (6, 28)], fill=_pal("K"))
    d.polygon([(9, 23), (22, 23), (23, 27), (8, 27)], fill=_pal("t"))
    return img


def building_compost_bin():
    img = Image.new("RGBA", (32, 32), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    d.polygon([(7, 12), (24, 12), (22, 28), (9, 28)], fill=_pal("K"))
    d.polygon([(8, 13), (23, 13), (21, 27), (10, 27)], fill=_pal("W"))
    for y in (16, 20, 24):
        d.line([(8, y), (23, y)], fill=_pal("w"))
    d.rectangle([6, 9, 25, 12], fill=_pal("K"))     # lid
    d.rectangle([7, 10, 24, 11], fill=_pal("w"))
    d.ellipse([13, 4, 19, 10], fill=_pal("L"))      # leaf on top
    d.ellipse([14, 5, 17, 9], fill=_pal("l"))
    return img


def building_feed_barrel():
    img = Image.new("RGBA", (16, 32), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    d.ellipse([2, 2, 13, 9], fill=_pal("K"))
    d.ellipse([3, 3, 12, 8], fill=_pal("w"))
    d.rectangle([2, 6, 13, 28], fill=_pal("K"))
    d.rectangle([3, 7, 12, 27], fill=_pal("W"))
    d.rectangle([3, 12, 12, 14], fill=_pal("K"))    # hoops
    d.rectangle([3, 21, 12, 23], fill=_pal("K"))
    d.rectangle([4, 8, 6, 27], fill=_pal("w"))      # stave shade
    d.ellipse([2, 25, 13, 31], fill=_pal("K"))
    d.ellipse([3, 26, 12, 30], fill=_pal("w"))
    return img


def building_hay_bed():
    img = Image.new("RGBA", (32, 32), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    d.ellipse([4, 14, 27, 28], fill=_pal("K"))
    d.ellipse([5, 15, 26, 27], fill=_pal("G"))
    for x, y in [(9, 19), (14, 22), (19, 19), (22, 23), (11, 24), (17, 24)]:
        d.line([(x, y), (x + 2, y - 3)], fill=_pal("F"))
    d.ellipse([10, 15, 20, 20], fill=_pal("N"))     # pillow
    d.ellipse([11, 16, 19, 19], fill=_pal("K"))
    return img


def building_ranch_fence():
    img = Image.new("RGBA", (32, 32), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    for x in (5, 14, 23):
        _outlined_rect(d, x, 8, x + 4, 26, "W")     # posts
        d.rectangle([x + 1, 9, x + 1, 25], fill=_pal("w"))
    for y in (12, 20):
        d.rectangle([3, y, 28, y + 3], fill=_pal("K"))
        d.rectangle([4, y + 1, 27, y + 2], fill=_pal("W"))
    return img


def building_table_workbench():
    img = Image.new("RGBA", (32, 32), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    d.rectangle([4, 12, 27, 17], fill=_pal("K"))    # top
    d.rectangle([5, 13, 26, 16], fill=_pal("W"))
    d.rectangle([6, 13, 12, 14], fill=_pal("w"))
    for x in (6, 23):
        d.rectangle([x, 17, x + 3, 28], fill=_pal("K"))
        d.rectangle([x + 1, 18, x + 2, 27], fill=_pal("w"))
    d.rectangle([6, 22, 26, 24], fill=_pal("K"))    # shelf
    d.rectangle([7, 23, 25, 23], fill=_pal("w"))
    d.rectangle([18, 8, 24, 12], fill=_pal("T"))    # hammer on top
    d.rectangle([20, 4, 22, 9], fill=_pal("W"))
    return img


def building_altar_stone():
    img = Image.new("RGBA", (48, 48), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    d.rectangle([8, 38, 39, 44], fill=_pal("K"))
    d.rectangle([9, 39, 38, 43], fill=_pal("t"))
    d.rectangle([12, 30, 35, 39], fill=_pal("K"))
    d.rectangle([13, 31, 34, 38], fill=_pal("T"))
    d.rectangle([17, 18, 30, 31], fill=_pal("K"))   # pillar
    d.rectangle([18, 19, 29, 30], fill=_pal("T"))
    d.rectangle([19, 20, 22, 29], fill=_pal("t"))
    d.rectangle([14, 12, 33, 18], fill=_pal("K"))   # cap
    d.rectangle([15, 13, 32, 17], fill=_pal("T"))
    d.polygon([(24, 2), (28, 10), (24, 14), (20, 10)], fill=_pal("A"))  # crystal
    d.polygon([(24, 2), (26, 10), (24, 14), (22, 10)], fill=_pal("N"))
    return img


BUILDINGS = {
    "assets/buildings/chest_wood.png": building_chest_wood,
    "assets/buildings/cooking_pot.png": building_cooking_pot,
    "assets/buildings/furnace_stove.png": building_furnace_stove,
    "assets/buildings/anvil.png": building_anvil,
    "assets/buildings/compost_bin.png": building_compost_bin,
    "assets/buildings/feed_barrel.png": building_feed_barrel,
    "assets/buildings/hay_bed.png": building_hay_bed,
    "assets/buildings/ranch_fence.png": building_ranch_fence,
    "assets/buildings/table_workbench.png": building_table_workbench,
    "assets/buildings/altar_stone.png": building_altar_stone,
}

# ---------------------------------------------------------------- tiles
import random


def _seeded(s):
    return random.Random(s)


def tile_grass_cell(d, ox, oy, rng):
    base = "L"
    for y in range(16):
        for x in range(16):
            r = rng.random()
            c = base
            if r < 0.12: c = "l"
            elif r < 0.18: c = "W" if rng.random() < 0.5 else "l"
            d.point((ox + x, oy + y), fill=_pal(c))
    # occasional blade tufts
    for _ in range(3):
        x, y = rng.randint(ox + 1, ox + 14), rng.randint(oy + 4, oy + 14)
        d.line([(x, y), (x, y - 2)], fill=_pal("l"))


def tile_world_grass_tiled():
    img = Image.new("RGBA", (256, 256), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    rng = _seeded(7)
    for cy in range(16):
        for cx in range(16):
            tile_grass_cell(d, cx * 16, cy * 16, rng)
    return img


def tile_camp_cobblestone():
    img = Image.new("RGBA", (128, 128), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    rng = _seeded(11)
    d.rectangle([0, 0, 127, 127], fill=_pal("t"))
    for cy in range(8):
        for cx in range(8):
            x0, y0 = cx * 16 + 1, cy * 16 + 1
            shade = "T" if rng.random() < 0.7 else "N"
            d.rounded_rectangle([x0, y0, x0 + 13, y0 + 13], radius=4, fill=_pal(shade))
            d.rounded_rectangle([x0 + 2, y0 + 2, x0 + 8, y0 + 8], radius=3, fill=_pal("N") if shade == "T" else _pal("T"))
    return img


def tile_floor_water():
    img = Image.new("RGBA", (16, 16), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    d.rectangle([0, 0, 15, 15], fill=_pal("A"))
    for x in (2, 7, 12):
        d.line([(x, 4), (x + 3, 4)], fill=_pal("N"))
        d.line([(x + 1, 11), (x + 4, 11)], fill=_pal("a"))
    return img


def tile_nature_boulder():
    img = Image.new("RGBA", (32, 32), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    d.ellipse([1, 6, 30, 30], fill=_pal("K"))
    d.ellipse([2, 7, 29, 29], fill=_pal("T"))
    d.ellipse([5, 9, 18, 20], fill=_pal("N"))
    d.line([(7, 24), (25, 24)], fill=_pal("t"))
    d.line([(11, 27), (21, 27)], fill=_pal("t"))
    return img


def tile_nature_bush():
    img = Image.new("RGBA", (32, 32), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    rng = _seeded(21)
    for (x, y, r) in [(10, 18, 8), (20, 16, 9), (15, 12, 7)]:
        d.ellipse([x - r, y - r, x + r, y + r], fill=_pal("K"))
        d.ellipse([x - r + 1, y - r + 1, x + r - 1, y + r - 1], fill=_pal("L"))
    for _ in range(10):
        x, y = rng.randint(8, 24), rng.randint(8, 24)
        d.point((x, y), fill=_pal("l"))
    d.ellipse([12, 10, 17, 15], fill=_pal("N"))
    d.rectangle([14, 24, 17, 28], fill=_pal("w"))  # trunk bit
    return img


def tile_nature_campfire():
    img = Image.new("RGBA", (32, 32), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    for i, sx in enumerate([8, 12, 16, 20]):
        d.ellipse([sx - 3, 20 - 3, sx + 3, 20 + 3], fill=_pal("T"))  # stone ring
    d.line([(9, 22), (23, 18)], fill=_pal("W"))
    d.line([(9, 18), (23, 22)], fill=_pal("w"))
    d.polygon([(16, 6), (20, 18), (12, 18)], fill=_pal("F"))
    d.polygon([(16, 10), (18, 18), (14, 18)], fill=_pal("G"))
    return img


def tile_nature_flowers():
    img = Image.new("RGBA", (32, 32), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    rng = _seeded(33)
    tile_grass_cell(d, 8, 8, rng)
    # clear the 16x16 area look: draw grass patch
    for (x, y, c) in [(12, 14, "R"), (20, 18, "G"), (16, 22, "N")]:
        d.line([(x, y), (x, y + 4)], fill=_pal("l"))
        for dx, dy in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
            d.point((x + dx, y + dy), fill=_pal(c))
        d.point((x, y), fill=_pal("G") if c != "G" else _pal("R"))
    return img


def tile_nature_mushrooms():
    img = Image.new("RGBA", (32, 32), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    rng = _seeded(44)
    for _ in range(40):
        d.point((rng.randint(8, 23), rng.randint(16, 27)), fill=_pal("l"))
    for (x, y, s) in [(13, 22, 5), (20, 24, 4)]:
        d.rectangle([x - 1, y, x + 1, y + 4], fill=_pal("N"))       # stem
        d.ellipse([x - s, y - s, x + s, y + 1], fill=_pal("R"))     # cap
        d.point((x - 2, y - 3), fill=_pal("N"))
        d.point((x + 1, y - 4), fill=_pal("N"))
    return img


def tile_nature_stump():
    img = Image.new("RGBA", (32, 32), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    d.ellipse([8, 16, 24, 28], fill=_pal("K"))
    d.ellipse([9, 17, 23, 27], fill=_pal("W"))
    d.ellipse([11, 18, 21, 25], fill=_pal("w"))
    d.ellipse([13, 19, 19, 23], fill=_pal("W"))
    for x in (10, 22):
        d.line([(x, 22), (x, 28)], fill=_pal("w"))
    return img


def tile_nature_tree_oak():
    img = Image.new("RGBA", (48, 48), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    rng = _seeded(55)
    d.rectangle([21, 30, 26, 46], fill=_pal("K"))
    d.rectangle([22, 31, 25, 45], fill=_pal("W"))
    d.rectangle([22, 31, 23, 45], fill=_pal("w"))
    for (x, y, r) in [(24, 16, 14), (14, 22, 9), (34, 22, 9), (24, 26, 10)]:
        d.ellipse([x - r, y - r, x + r, y + r], fill=_pal("K"))
        d.ellipse([x - r + 1, y - r + 1, x + r - 1, y + r - 1], fill=_pal("L"))
    for _ in range(24):
        x, y = rng.randint(12, 36), rng.randint(6, 30)
        d.point((x, y), fill=_pal("l"))
    d.ellipse([18, 8, 26, 16], fill=_pal("N"))
    return img


def tile_pal_crystal_ore():
    img = Image.new("RGBA", (16, 16), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    d.polygon([(2, 14), (6, 6), (10, 14)], fill=_pal("K"))
    d.polygon([(3, 13), (6, 7), (9, 13)], fill=_pal("T"))
    d.polygon([(8, 14), (11, 4), (14, 14)], fill=_pal("K"))
    d.polygon([(9, 13), (11, 5), (13, 13)], fill=_pal("A"))
    d.polygon([(10, 12), (11, 7), (12, 12)], fill=_pal("N"))
    return img


def tile_tileset_field():
    # 80x240 farm atlas: every 16x16 cell is tilled soil; rows carry crop stages
    img = Image.new("RGBA", (80, 240), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    rng = _seeded(66)
    for cy in range(15):
        for cx in range(5):
            ox, oy = cx * 16, cy * 16
            d.rectangle([ox, oy, ox + 15, oy + 15], fill=_pal("K"))
            for y in range(1, 15):
                for x in range(1, 15):
                    r = rng.random()
                    c = "w" if r < 0.7 else ("W" if r < 0.9 else "K")
                    d.point((ox + x, oy + y), fill=_pal(c))
            # crop growth overlay by row band
            band = cy % 5
            if band >= 1:
                for px in range(3, 14, 4):
                    h = band * 2
                    d.line([(ox + px, oy + 13), (ox + px, oy + 13 - h)], fill=_pal("l"))
                    if band >= 3:
                        d.point((ox + px, oy + 12 - h), fill=_pal("G"))
    return img


TILES = {
    "assets/tilesets/world_grass_tiled.png": tile_world_grass_tiled,
    "assets/tilesets/camp_cobblestone.png": tile_camp_cobblestone,
    "assets/tilesets/floor_water.png": tile_floor_water,
    "assets/tilesets/nature_boulder.png": tile_nature_boulder,
    "assets/tilesets/nature_bush.png": tile_nature_bush,
    "assets/tilesets/nature_campfire.png": tile_nature_campfire,
    "assets/tilesets/nature_flowers.png": tile_nature_flowers,
    "assets/tilesets/nature_mushrooms.png": tile_nature_mushrooms,
    "assets/tilesets/nature_stump.png": tile_nature_stump,
    "assets/tilesets/nature_tree_oak.png": tile_nature_tree_oak,
    "assets/tilesets/pal_crystal_ore.png": tile_pal_crystal_ore,
    "assets/tilesets/tileset_field.png": tile_tileset_field,
}

# ---------------------------------------------------------------- FX
def _glow_circle(size, inner, mid):
    img = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    c = size // 2
    for r in range(c, 0, -1):
        t = r / c
        if t > 0.55:
            col = mid
        elif t > 0.25:
            col = inner
        else:
            col = "N"
        d.ellipse([c - r, c - r, c + r, c + r], fill=_pal(col))
    return img


def fx_frame_orb(frame, total, size, col1, col2):
    img = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    c = size // 2
    rad = c - 2 - (frame % 2)
    d.ellipse([c - rad, c - rad, c + rad, c + rad], fill=_pal("K"))
    d.ellipse([c - rad + 1, c - rad + 1, c + rad - 1, c + rad - 1], fill=_pal(col1))
    d.ellipse([c - rad + 3, c - rad + 3, c + rad - 3, c + rad - 3], fill=_pal(col2))
    d.point((c - 2, c - 2), fill=_pal("N"))
    # motion streak
    for i in range(frame):
        d.point((2 + i * 2, c), fill=_pal(col1))
    return img


def fx_energy_ball():
    strip = Image.new("RGBA", (64, 16), (0, 0, 0, 0))
    for i in range(4):
        strip.paste(fx_frame_orb(i, 4, 16, "A", "N"), (i * 16, 0),
                    fx_frame_orb(i, 4, 16, "A", "N"))
    return strip


def fx_fireball():
    strip = Image.new("RGBA", (64, 16), (0, 0, 0, 0))
    for i in range(4):
        f = fx_frame_orb(i, 4, 16, "F", "G")
        strip.paste(f, (i * 16, 0), f)
    return strip


def fx_big_energy_ball():
    strip = Image.new("RGBA", (96, 24), (0, 0, 0, 0))
    for i in range(4):
        f = fx_frame_orb(i, 4, 24, "B", "N")
        strip.paste(f, (i * 24, 0), f)
    return strip


def fx_slash_sheet():
    strip = Image.new("RGBA", (128, 32), (0, 0, 0, 0))
    d_all = ImageDraw.Draw(strip)
    for i in range(4):
        ox = i * 32
        d = ImageDraw.Draw(strip)
        # arc slash sweeping across the frame
        x0 = 4 + i * 7
        d.arc([ox + x0 - 10, 4, ox + x0 + 10, 28], start=200, end=340, fill=_pal("N"), width=3)
        d.arc([ox + x0 - 10, 4, ox + x0 + 10, 28], start=210, end=330, fill=_pal("A"), width=1)
    return strip


def fx_dust():
    img = Image.new("RGBA", (8, 8), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    d.ellipse([1, 2, 6, 7], fill=_pal("T"))
    d.ellipse([2, 3, 5, 6], fill=_pal("N"))
    return img


def fx_leaf():
    img = Image.new("RGBA", (8, 8), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    d.polygon([(4, 0), (7, 4), (4, 7), (1, 4)], fill=_pal("L"))
    d.line([(4, 1), (4, 6)], fill=_pal("l"))
    return img


def fx_spark():
    img = Image.new("RGBA", (8, 8), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    d.line([(4, 0), (4, 7)], fill=_pal("G"))
    d.line([(0, 4), (7, 4)], fill=_pal("G"))
    d.point((4, 4), fill=_pal("N"))
    return img


def fx_shadow():
    img = Image.new("RGBA", (24, 16), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    d.ellipse([1, 3, 22, 12], fill=(29, 36, 51, 110))
    return img


def fx_light_radial():
    img = Image.new("RGBA", (128, 128), (0, 0, 0, 0))
    px = img.load()
    c = 64
    for y in range(128):
        for x in range(128):
            dist = ((x - c) ** 2 + (y - c) ** 2) ** 0.5 / c
            if dist <= 1.0:
                a = int(140 * (1.0 - dist) ** 1.6)
                px[x, y] = (242, 194, 48, a)
    return img


FX = {
    "assets/fx/energy_ball.png": fx_energy_ball,
    "assets/fx/fireball.png": fx_fireball,
    "assets/fx/big_energy_ball.png": fx_big_energy_ball,
    "assets/fx/slash_sheet.png": fx_slash_sheet,
    "assets/fx/dust.png": fx_dust,
    "assets/fx/leaf.png": fx_leaf,
    "assets/fx/spark.png": fx_spark,
    "assets/fx/shadow.png": fx_shadow,
    "assets/fx/light_radial.png": fx_light_radial,
}


# ---------------------------------------------------------------- main
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True, help="output directory for PNGs")
    args = ap.parse_args()
    os.makedirs(args.out, exist_ok=True)
    manifest = []
    # items
    for name, rows in ITEMS.items():
        rel = "assets/items/%s.png" % name
        img = from_ascii(rows)
        img.save(os.path.join(args.out, "items_%s.png" % name))
        manifest.append({"path": rel, "width": 16, "height": 16})
    strip = Image.new("RGBA", (64, 16), (0, 0, 0, 0))
    for i, rows in enumerate(CROP_STAGES):
        f = from_ascii(rows)
        strip.paste(f, (i * 16, 0), f)
    strip.save(os.path.join(args.out, "items_crop_stages.png"))
    manifest.append({"path": "assets/items/crop_stages.png", "width": 64, "height": 16})
    for rel, fn in list(BUILDINGS.items()) + list(TILES.items()) + list(FX.items()):
        img = fn()
        flat = "misc_" + rel.replace("assets/", "").replace("/", "_")
        img.save(os.path.join(args.out, flat))
        manifest.append({"path": rel, "width": img.size[0], "height": img.size[1]})
    with open(os.path.join(args.out, "generation_manifest.json"), "w") as fh:
        json.dump(manifest, fh, indent=1)
    print("generated %d sprites -> %s" % (len(manifest), args.out))


if __name__ == "__main__":
    main()
