#!/usr/bin/env python3
"""Generate original CC0 town art for Paloria Luminous Town (AT-B, refreshed).

Anime-town pixel art drawn with PIL. Every pixel color is constrained to the
validator palette (PALORIA16 + AT town extensions, see
tools/validate_town_art.py) so the art gate stays green. Canvas sizes match the
greybox footprints in systems/town/town_layout.gd exactly.

Provenance: GENERATED by project tool, license CC0-1.0, author "Paloria project".
Third-party evaluation (2026-10-08): Kenney "Tiny Town"/"Tiny Dungeon"/
"Tiny Farm" packs (CC0-1.0, kenney.nl) were downloaded and evaluated as a
sprite source. Rejected for direct use: western-medieval style clashes with the
anime/Japanese town direction (torii, shrine, sakura, vending machines), and
the character sprites are single-frame with no 4-direction walk cycles, so they
cannot satisfy the hero/pet animation contracts. Original art keeps the style
coherent and the provenance clean.

Usage:
    python3 tools/generate_town_art.py --out /tmp/paloria_town
"""
import argparse
import json
import math
import os
import random

from PIL import Image, ImageDraw

# ---------------------------------------------------------------- palette
# All entries are validator-legal: PALORIA16 + AT_EXTENSIONS.
PAL = {
    "K":      (29, 36, 51),    # 1D2433 outline
    "cream":  (240, 230, 210), # F0E6D2 (strict validator set)
    "brown":  (169, 116, 79),   # A9744F (strict validator set)
    "tan":    (247, 217, 160), # F7D9A0 (strict validator set)
    "gold":   (242, 194, 48),  # F2C230
    "orange": (242, 129, 46),  # F2812E
    "red":    (214, 64, 94),   # D6405E
    "green":  (79, 174, 79),   # 4FAE4F
    "greend": (47, 125, 58),   # 2F7D3A
    "sky":    (63, 167, 214),  # 3FA7D6
    "blued":  (36, 116, 163),  # 2474A3
    "white":  (238, 243, 248), # EEF3F8
    "ochre":  (201, 111, 46),  # C96F2E (strict validator set)
    "grey":   (138, 148, 166), # 8A94A6 (strict validator set)
    "greyd":  (107, 114, 128), # 6B7280
    "char":   (43, 51, 85),    # 2B3355 (in town-val + strict sets)
    "roof":   (63, 95, 138),   # 3F5F8A
    "roofd":  (44, 68, 99),    # 2C4463
    "plas":   (240, 230, 210), # F0E6D2
    "plasd":  (217, 201, 168), # D9C9A8
    "torii":  (192, 57, 43),   # C0392B
    "toriid": (142, 42, 32),   # 8E2A20
    "paper":  (247, 217, 160), # F7D9A0
    "glow":   (255, 179, 71),  # FFB347
    "sakura": (242, 167, 195), # F2A7C3
    "sakurad": (214, 127, 158),# D67F9E
    "night":  (43, 51, 85),    # 2B3355
    "purple": (122, 95, 160),  # 7A5FA0
    "stonel": (138, 148, 166), # 8A94A6
    "wood":   (169, 116, 79),  # A9744F
    "woodd":  (122, 82, 51),   # 7A5233
    "stone":  (154, 163, 178), # 9AA3B2
}


def C(name):
    return PAL[name] + (255,)


def new(w, h):
    return Image.new("RGBA", (w, h), (0, 0, 0, 0))


def rng(seed):
    return random.Random(seed)


# ---------------------------------------------------------------- helpers
def rect(d, x0, y0, x1, y1, fill, outline=None, ow=1):
    """Filled rect with optional outline. fill=None draws outline only."""
    if outline is not None:
        d.rectangle([x0, y0, x1, y1], fill=C(outline))
        if fill is not None:
            d.rectangle([x0 + ow, y0 + ow, x1 - ow, y1 - ow], fill=C(fill))
    elif fill is not None:
        d.rectangle([x0, y0, x1, y1], fill=C(fill))


def dither_v(d, x0, y0, x1, y1, c_top, c_bottom):
    """Vertical dithered gradient between two palette colors."""
    h = max(1, y1 - y0)
    for y in range(y0, y1 + 1):
        t = (y - y0) / h
        for x in range(x0, x1 + 1):
            if ((x + y) % 2 == 0 and t < 0.5) or ((x * 7 + y * 13) % 10 < t * 10):
                d.point((x, y), fill=C(c_bottom))
            else:
                d.point((x, y), fill=C(c_top))


def speckle(d, x0, y0, x1, y1, colors, r, n):
    for _ in range(n):
        x = r.randint(x0, x1)
        y = r.randint(y0, y1)
        d.point((x, y), fill=C(r.choice(colors)))


def bricks(d, x0, y0, x1, y1, bh, brick, mortar, r, speck=True):
    """Brick courses with offset rows."""
    rect(d, x0, y0, x1, y1, mortar)
    row = 0
    y = y0
    while y < y1:
        off = (row % 2) * 6
        for x in range(x0 - 12 + off, x1 + 1, 12):
            bx0, bx1 = max(x, x0), min(x + 10, x1)
            by0, by1 = y + 1, min(y + bh - 1, y1)
            if bx1 > bx0 and by1 > by0:
                rect(d, bx0, by0, bx1, by1, brick)
                if speck and r.random() < 0.5:
                    d.point((r.randint(bx0 + 1, bx1), r.randint(by0 + 1, by1)),
                            fill=C(mortar))
        y += bh
        row += 1


def planks_v(d, x0, y0, x1, y1, wood, woodd, r, pw=6):
    """Vertical wood planks with grain."""
    rect(d, x0, y0, x1, y1, wood)
    for x in range(x0, x1 + 1, pw):
        d.line([(x, y0), (x, y1)], fill=C(woodd))
        gx1 = min(x + pw - 2, x1)
        if gx1 <= x + 1:
            continue
        for _ in range((y1 - y0) // 9):
            gx = r.randint(x + 1, gx1)
            gy = r.randint(y0 + 2, y1 - 2)
            d.line([(gx, gy), (gx, gy + 3)], fill=C(woodd))


def planks_h(d, x0, y0, x1, y1, wood, woodd, r, ph=5):
    rect(d, x0, y0, x1, y1, wood)
    for y in range(y0, y1 + 1, ph):
        d.line([(x0, y), (x1, y)], fill=C(woodd))


def window(d, x, y, w, h, lit=False):
    """Lattice window: dark frame, glass with diagonal reflection."""
    rect(d, x, y, x + w, y + h, "night", outline="K", ow=1)
    gx0, gy0, gx1, gy1 = x + 2, y + 2, x + w - 2, y + h - 2
    glass = "glow" if lit else "night"
    rect(d, gx0, gy0, gx1, gy1, glass)
    if not lit:
        # sky reflection diagonal
        for i in range(min(w, h) - 3):
            d.point((gx0 + 1 + i, gy0 + 1 + i), fill=C("sky"))
            if i + 1 < min(w, h) - 3:
                d.point((gx0 + 2 + i, gy0 + 1 + i), fill=C("blued"))
    # mullions
    d.line([(x + w // 2, gy0), (x + w // 2, gy1)], fill=C("K"))
    d.line([(gx0, y + h // 2), (gx1, y + h // 2)], fill=C("K"))
    # sill
    rect(d, x - 1, y + h + 1, x + w + 1, y + h + 3, "woodd", outline="K", ow=1)


def star(d, cx, cy, r, col):
    pts = []
    for i in range(10):
        ang = -math.pi / 2 + i * math.pi / 5
        rr = r if i % 2 == 0 else r * 0.45
        pts.append((cx + rr * math.cos(ang), cy + rr * math.sin(ang)))
    d.polygon(pts, fill=C(col))

# ---------------------------------------------------------------- houses
def _japan_roof(d, cx, y_apex, half_base, y_eave, r, tile="roof", tiled="roofd"):
    """Tiled gable roof with ridge caps and flared eaves."""
    # main slope
    d.polygon([(cx - half_base, y_eave), (cx, y_apex), (cx + half_base, y_eave)],
              fill=C("K"))
    d.polygon([(cx - half_base + 3, y_eave - 2), (cx, y_apex + 4),
               (cx + half_base - 3, y_eave - 2)], fill=C(tile))
    # tile rows
    rows = max(2, (y_eave - y_apex) // 8)
    for i in range(rows):
        t0 = i / rows
        t1 = (i + 1) / rows
        ya = int(y_apex + (y_eave - y_apex) * t0) + 2
        yb = int(y_apex + (y_eave - y_apex) * t1) + 2
        h0 = half_base * (1 - t0 * 0.92)
        h1 = half_base * (1 - t1 * 0.92)
        n = max(3, int(h1 * 2 / 8))
        for k in range(n):
            tx = cx - h1 + (2 * h1) * (k + 0.5) / n
            d.arc([tx - 4, yb - 5, tx + 4, yb + 3], 0, 180, fill=C(tiled))
        d.line([(cx - h1, yb), (cx + h1, yb)], fill=C(tiled))
    # ridge caps
    for k in range(-2, 3):
        d.ellipse([cx + k * 8 - 4, y_apex - 2, cx + k * 8 + 4, y_apex + 6],
                  fill=C(tiled), outline=C("K"))
    # flared eaves
    d.polygon([(cx - half_base - 6, y_eave + 2), (cx - half_base + 4, y_eave - 6),
               (cx + half_base - 4, y_eave - 6), (cx + half_base + 6, y_eave + 2)],
              fill=C("K"))
    d.polygon([(cx - half_base - 4, y_eave), (cx - half_base + 4, y_eave - 4),
               (cx + half_base - 4, y_eave - 4), (cx + half_base + 4, y_eave)],
              fill=C(tiled))


def _machiya_walls(d, x0, y0, x1, y1, r):
    """Plaster walls with dark wood frame (machiya style)."""
    rect(d, x0, y0, x1, y1, "plas", outline="K", ow=2)
    # subtle plaster texture
    speckle(d, x0 + 3, y0 + 3, x1 - 3, y1 - 3, ["plasd"], r, 40)
    # corner posts + beams
    for x in (x0 + 2, x1 - 4):
        rect(d, x, y0, x + 2, y1, "woodd")
    rect(d, x0, y0, x1, y0 + 4, "woodd")      # top beam
    rect(d, x0, y1 - 6, x1, y1 - 2, "woodd")  # bottom beam
    # wood grain on beams
    for x in range(x0 + 6, x1 - 4, 8):
        d.point((x, y0 + 2), fill=C("wood"))


def house_a():
    """128x112 machiya town house: plaster + wood frame, tiled roof."""
    img = new(128, 112)
    d = ImageDraw.Draw(img)
    r = rng(101)
    cx = 64
    # stone foundation
    bricks(d, 22, 96, 106, 108, 6, "stone", "greyd", r)
    rect(d, 22, 96, 106, 108, None, outline="K", ow=2)
    # walls
    _machiya_walls(d, 26, 48, 102, 98, r)
    # wooden sliding door with panels
    rect(d, 56, 68, 76, 98, "wood", outline="K", ow=2)
    planks_v(d, 58, 70, 74, 96, "wood", "woodd", r, pw=5)
    rect(d, 60, 74, 72, 84, "woodd", outline="K", ow=1)  # panel
    d.ellipse([70, 88, 73, 91], fill=C("gold"), outline=C("K"))  # knob
    # lattice windows
    window(d, 32, 62, 16, 18)
    window(d, 82, 62, 16, 18)
    # noren curtain over door
    for i, col in enumerate(["torii", "white", "torii"]):
        x0 = 54 + i * 8
        d.polygon([(x0, 60), (x0 + 8, 60), (x0 + 7, 70), (x0 + 1, 70)], fill=C(col),
                  outline=C("K"))
    # roof
    _japan_roof(d, cx, 6, 56, 50, r)
    # wall shadow under eaves
    dither_v(d, 26, 48, 102, 54, "plasd", "plas")
    return img


def house_b():
    """128x112 shop: house_a + striped awning, sign, display window."""
    img = house_a()
    d = ImageDraw.Draw(img)
    r = rng(102)
    # awning
    d.polygon([(18, 58), (110, 58), (102, 74), (26, 74)], fill=C("K"))
    for i in range(7):
        x0 = 22 + i * 12
        col = "red" if i % 2 == 0 else "white"
        d.polygon([(x0, 60), (x0 + 12, 60), (x0 + 10, 72), (x0 + 2, 72)], fill=C(col))
        d.arc([x0 + 1, 66, x0 + 11, 76], 0, 180, fill=C("K"))
    # hanging sign
    d.line([(96, 58), (96, 66)], fill=C("K"), width=2)
    rect(d, 84, 66, 108, 80, "woodd", outline="K", ow=2)
    rect(d, 86, 68, 106, 78, "paper")
    star(d, 96, 73, 4, "gold")
    # display window with goods
    window(d, 30, 62, 20, 18, lit=True)
    for gx, col in [(34, "red"), (40, "orange"), (46, "green")]:
        d.ellipse([gx, 72, gx + 5, 77], fill=C(col), outline=C("K"))
    # crates beside door
    rect(d, 104, 84, 118, 98, "wood", outline="K", ow=2)
    d.line([(104, 91), (118, 91)], fill=C("woodd"))
    d.line([(111, 84), (111, 98)], fill=C("woodd"))
    speckle(d, 106, 86, 116, 96, ["woodd"], r, 8)
    return img


# ---------------------------------------------------------------- station
def station_hall():
    """220x120 station hall: long tiled roof, window row, clock, sign."""
    img = new(220, 120)
    d = ImageDraw.Draw(img)
    r = rng(103)
    cx = 110
    # foundation
    bricks(d, 18, 100, 202, 112, 6, "stone", "greyd", r)
    # walls
    _machiya_walls(d, 22, 44, 198, 102, r)
    # window row with warm lit glass
    for x in range(32, 186, 30):
        window(d, x, 58, 18, 20, lit=(x % 60 == 32))
    # double doors
    rect(d, 100, 72, 122, 102, "wood", outline="K", ow=2)
    d.line([(111, 72), (111, 102)], fill=C("K"))
    planks_v(d, 102, 74, 120, 100, "wood", "woodd", r, pw=6)
    for hx in (106, 116):
        d.ellipse([hx, 86, hx + 3, 89], fill=C("gold"), outline=C("K"))
    # station sign board with star + posts
    rect(d, 86, 30, 134, 46, "woodd", outline="K", ow=2)
    rect(d, 88, 32, 132, 44, "paper")
    star(d, 110, 38, 6, "torii")
    # round clock on wall
    d.ellipse([150, 78, 172, 100], fill=C("K"))
    d.ellipse([152, 80, 170, 98], fill=C("white"))
    for ang in range(0, 360, 30):
        a = math.radians(ang)
        d.line([(161 + 7 * math.cos(a), 89 + 7 * math.sin(a)),
                (161 + 9 * math.cos(a), 89 + 9 * math.sin(a))], fill=C("K"))
    d.line([(161, 89), (161, 84)], fill=C("red"), width=2)
    d.line([(161, 89), (165, 91)], fill=C("K"), width=2)
    d.point((161, 89), fill=C("gold"))
    # big roof
    _japan_roof(d, cx, 4, 104, 46, r)
    dither_v(d, 22, 44, 198, 52, "plasd", "plas")
    return img


def clock_tower():
    """64x160 clock tower: brick shaft, clock, belfry, spire."""
    img = new(64, 160)
    d = ImageDraw.Draw(img)
    r = rng(104)
    # shaft
    bricks(d, 16, 44, 48, 150, 7, "plas", "plasd", r)
    rect(d, 16, 44, 48, 150, None, outline="K", ow=2)
    # stone base
    bricks(d, 14, 132, 50, 152, 6, "stone", "greyd", r)
    # clock face
    d.ellipse([12, 50, 52, 90], fill=C("K"))
    d.ellipse([15, 53, 49, 87], fill=C("white"))
    d.ellipse([15, 53, 49, 87], outline=C("gold"))
    for ang in range(0, 360, 30):
        a = math.radians(ang)
        w = 2 if ang % 90 == 0 else 1
        d.line([(32 + 13 * math.cos(a), 70 + 13 * math.sin(a)),
                (32 + 16 * math.cos(a), 70 + 16 * math.sin(a))], fill=C("K"), width=w)
    d.line([(32, 70), (32, 60)], fill=C("red"), width=2)
    d.line([(32, 70), (39, 73)], fill=C("K"), width=2)
    d.ellipse([30, 68, 34, 72], fill=C("gold"), outline=C("K"))
    # belfry with arched openings + bell
    rect(d, 12, 18, 52, 44, "woodd", outline="K", ow=2)
    for x in (17, 37):
        d.pieslice([x, 24, x + 10, 42], 180, 360, fill=C("night"), outline=C("K"))
        rect(d, x, 32, x + 10, 42, "night", outline="K", ow=1)
    d.polygon([(32, 26), (38, 38), (26, 38)], fill=C("gold"), outline=C("K"))
    d.ellipse([29, 36, 35, 40], fill=C("gold"), outline=C("K"))
    # spire
    d.polygon([(32, 0), (54, 20), (10, 20)], fill=C("K"))
    d.polygon([(32, 4), (50, 18), (14, 18)], fill=C("roof"))
    d.line([(32, 4), (32, 18)], fill=C("roofd"))
    star(d, 32, 12, 3, "gold")
    # door
    rect(d, 26, 112, 38, 132, "wood", outline="K", ow=2)
    planks_v(d, 28, 114, 36, 130, "wood", "woodd", r, pw=4)
    # ivy
    for i in range(6):
        x, y = 16 + (i * 7) % 30, 96 + i * 6
        d.ellipse([x, y, x + 5, y + 4], fill=C("green"), outline=C("greend"))
    return img


def platform():
    """320x40 platform: stone slabs, white edge, warning strip."""
    img = new(320, 40)
    d = ImageDraw.Draw(img)
    r = rng(105)
    rect(d, 0, 0, 319, 39, "stone", outline="K", ow=2)
    # slabs with perspective seams
    for x in range(0, 320, 40):
        d.line([(x, 10), (x, 38)], fill=C("greyd"))
        d.line([(x + 1, 10), (x + 1, 38)], fill=C("stonel"))
    d.line([(0, 24), (319, 24)], fill=C("greyd"))
    speckle(d, 2, 12, 317, 37, ["stonel", "greyd"], r, 120)
    # white edge + yellow warning strip with black dashes
    rect(d, 2, 2, 317, 9, "white")
    rect(d, 2, 10, 317, 15, "gold")
    for x in range(4, 316, 16):
        d.rectangle([x, 11, x + 8, 14], fill=C("K"))
    d.line([(2, 16), (317, 16)], fill=C("K"))
    return img

# ---------------------------------------------------------------- market
def stall():
    """96x64 yatai market stall: posts, striped awning, goods, lantern."""
    img = new(96, 64)
    d = ImageDraw.Draw(img)
    r = rng(106)
    # posts
    for x in (10, 80):
        rect(d, x, 16, x + 6, 62, "wood", outline="K", ow=1)
        planks_v(d, x + 1, 18, x + 5, 60, "wood", "woodd", r, pw=4)
    # awning with scalloped edge
    d.polygon([(2, 20), (94, 20), (84, 2), (12, 2)], fill=C("K"))
    for i in range(9):
        x0 = 6 + i * 9
        col = "red" if i % 2 == 0 else "white"
        d.polygon([(x0, 18), (x0 + 9, 18), (x0 + 8, 4), (x0 + 1, 4)], fill=C(col))
        d.arc([x0, 12, x0 + 9, 21], 0, 180, fill=C("K"))
    # counter with cloth
    rect(d, 12, 38, 84, 62, "wood", outline="K", ow=2)
    planks_h(d, 14, 44, 82, 60, "wood", "woodd", r)
    d.polygon([(12, 38), (84, 38), (80, 46), (16, 46)], fill=C("torii"))
    d.polygon([(12, 38), (84, 38), (80, 42), (16, 42)], fill=C("red"))
    # goods: fruit piles + boxes
    piles = [(20, "red"), (30, "orange"), (40, "gold"), (52, "green")]
    for x, col in piles:
        for dx, dy in [(0, 0), (5, 0), (2, -4)]:
            d.ellipse([x + dx, 30 + dy, x + dx + 6, 36 + dy], fill=C(col),
                      outline=C("K"))
        d.point((x + 3, 31), fill=C("white"))
    rect(d, 62, 30, 78, 38, "paper", outline="K", ow=1)
    d.line([(62, 34), (78, 34)], fill=C("K"))
    # hanging paper lantern
    d.line([(48, 20), (48, 26)], fill=C("K"))
    d.ellipse([42, 26, 54, 38], fill=C("K"))
    d.ellipse([43, 27, 53, 37], fill=C("paper"))
    d.ellipse([46, 29, 50, 35], fill=C("glow"))
    rect(d, 44, 24, 52, 27, "woodd", outline="K", ow=1)
    return img


def bulletin():
    """48x64 bulletin board with roof cap and pinned notes."""
    img = new(48, 64)
    d = ImageDraw.Draw(img)
    r = rng(107)
    # posts
    for x in (6, 37):
        rect(d, x, 32, x + 5, 62, "woodd", outline="K", ow=1)
    # board
    rect(d, 2, 8, 46, 36, "wood", outline="K", ow=2)
    planks_h(d, 4, 10, 44, 34, "wood", "woodd", r)
    # pinned notes
    notes = [(7, 13, "paper"), (20, 12, "white"), (33, 14, "paper"),
             (9, 24, "white"), (24, 24, "paper")]
    for x, y, col in notes:
        d.polygon([(x, y), (x + 10, y + 1), (x + 9, y + 9), (x - 1, y + 8)],
                  fill=C(col), outline=C("K"))
        d.point((x + 4, y + 2), fill=C("red"))  # pin
        d.line([(x + 2, y + 5), (x + 7, y + 5)], fill=C("greyd"))
        d.line([(x + 2, y + 7), (x + 6, y + 7)], fill=C("greyd"))
    # little roof cap
    d.polygon([(0, 10), (24, 0), (48, 10)], fill=C("K"))
    d.polygon([(4, 9), (24, 2), (44, 9)], fill=C("roof"))
    star(d, 24, 6, 3, "gold")
    return img


def vending():
    """40x64 vending machine: lit glass front, cans, pickup flap."""
    img = new(40, 64)
    d = ImageDraw.Draw(img)
    r = rng(108)
    # body
    rect(d, 4, 2, 36, 62, "red", outline="K", ow=2)
    dither_v(d, 6, 4, 34, 60, "red", "toriid")
    # top brand strip
    rect(d, 6, 4, 34, 10, "white", outline="K", ow=1)
    star(d, 20, 7, 3, "red")
    # glass front with drinks
    rect(d, 7, 13, 26, 40, "night", outline="K", ow=2)
    dither_v(d, 9, 15, 24, 38, "blued", "night")
    for yi, row in enumerate([(14, "red"), (22, "orange"), (30, "sky")]):
        y, col = row
        for x in (11, 16, 21):
            rect(d, x, y, x + 4, y + 6, col, outline="K", ow=1)
            d.line([(x + 1, y + 1), (x + 3, y + 1)], fill=C("white"))
    # glass reflection
    d.polygon([(9, 38), (15, 15), (19, 15), (13, 38)], fill=C("white"))
    # side panel: buttons + price
    rect(d, 28, 13, 34, 30, "char", outline="K", ow=1)
    for y in (17, 22, 27):
        d.ellipse([30, y, 32, y + 2], fill=C("glow"), outline=C("K"))
    # pickup flap
    rect(d, 7, 44, 33, 56, "char", outline="K", ow=2)
    rect(d, 9, 46, 31, 50, "night")
    d.line([(9, 50), (31, 50)], fill=C("greyd"))
    # feet + glow strip at base
    rect(d, 6, 58, 34, 60, "glow", outline="K", ow=1)
    rect(d, 8, 61, 12, 63, "K")
    rect(d, 28, 61, 32, 63, "K")
    return img

# ---------------------------------------------------------------- shrine
def torii():
    """96x96 vermilion torii gate with black caps and gold plaque."""
    img = new(96, 96)
    d = ImageDraw.Draw(img)
    r = rng(109)
    # pillars
    for x in (22, 64):
        rect(d, x, 30, x + 10, 94, "torii", outline="K", ow=2)
        dither_v(d, x + 2, 32, x + 8, 92, "torii", "toriid")
        rect(d, x + 3, 32, x + 5, 92, "red")  # highlight
        # base ring + foot stone
        rect(d, x - 2, 84, x + 12, 90, "char", outline="K", ow=1)
        rect(d, x - 3, 90, x + 13, 95, "stone", outline="K", ow=1)
    # second lintel (nuki)
    rect(d, 12, 40, 84, 50, "torii", outline="K", ow=2)
    dither_v(d, 14, 42, 82, 48, "torii", "toriid")
    # top lintel (shimaki) with upward curve
    d.polygon([(6, 30), (90, 30), (86, 12), (10, 12)], fill=C("K"))
    d.polygon([(9, 28), (87, 28), (83, 15), (13, 15)], fill=C("torii"))
    dither_v(d, 13, 16, 83, 27, "torii", "toriid")
    # black caps on lintel ends
    for x in (6, 86):
        d.polygon([(x, 30), (x + 4, 30), (x + 4, 12), (x, 12)], fill=C("K"))
    # center plaque with gold emblem
    rect(d, 41, 16, 55, 28, "char", outline="gold", ow=1)
    star(d, 48, 22, 4, "gold")
    # strut between lintels
    rect(d, 44, 30, 52, 40, "toriid", outline="K", ow=1)
    return img


def shrine_hall():
    """192x128 shrine: sweeping tiled roof, red pillars, shimenawa."""
    img = new(192, 128)
    d = ImageDraw.Draw(img)
    r = rng(110)
    cx = 96
    # stone stairs
    for i in range(3):
        y0 = 106 + i * 6
        rect(d, 66 + i * 5, y0, 126 - i * 5, y0 + 6, "stone", outline="K", ow=1)
        speckle(d, 68 + i * 5, y0 + 1, 124 - i * 5, y0 + 5, ["stonel", "greyd"],
                r, 14)
    # base platform
    rect(d, 52, 96, 140, 108, "woodd", outline="K", ow=2)
    planks_h(d, 54, 98, 138, 106, "woodd", "char", r)
    # pillars
    for x in (58, 128):
        rect(d, x, 56, x + 10, 98, "torii", outline="K", ow=2)
        dither_v(d, x + 2, 58, x + 8, 96, "torii", "toriid")
        rect(d, x + 3, 58, x + 5, 96, "red")
    # white walls with lattice
    rect(d, 68, 60, 124, 98, "plas", outline="K", ow=2)
    speckle(d, 70, 62, 122, 96, ["plasd"], r, 30)
    # lattice doors
    for dx in (78, 102):
        rect(d, dx, 70, dx + 14, 98, "wood", outline="K", ow=1)
        for ly in range(74, 96, 6):
            d.line([(dx + 1, ly), (dx + 13, ly)], fill=C("woodd"))
        d.line([(dx + 7, 70), (dx + 7, 98)], fill=C("woodd"))
    # offering box
    rect(d, 86, 88, 106, 98, "woodd", outline="K", ow=1)
    d.line([(86, 93), (106, 93)], fill=C("K"))
    # shimenawa rope with paper shide
    d.line([(58, 58), (138, 58)], fill=C("tan"), width=3)
    d.line([(58, 58), (138, 58)], fill=C("cream"), width=1)
    for x in (74, 96, 118):
        d.polygon([(x - 4, 60), (x + 4, 60), (x, 70), (x - 2, 64), (x - 6, 68)],
                  fill=C("white"), outline=C("K"))
    # hanging lanterns
    for x in (50, 142):
        d.line([(x, 52), (x, 60)], fill=C("K"), width=2)
        d.ellipse([x - 8, 60, x + 8, 76], fill=C("K"))
        d.ellipse([x - 6, 62, x + 6, 74], fill=C("paper"))
        d.ellipse([x - 3, 64, x + 3, 72], fill=C("glow"))
        rect(d, x - 5, 58, x + 5, 62, "char", outline="K", ow=1)
    # grand sweeping roof
    d.polygon([(20, 62), (cx, 8), (172, 62)], fill=C("K"))
    d.polygon([(26, 60), (cx, 14), (166, 60)], fill=C("roofd"))
    # tile rows on the slope
    for i in range(4):
        t = (i + 1) / 5
        ya = int(14 + (58 - 14) * t)
        h = (166 - 26) / 2 * (1 - t * 0.9)
        n = max(4, int(h * 2 / 10))
        for k in range(n):
            tx = cx - h + (2 * h) * (k + 0.5) / n
            d.arc([tx - 5, ya - 6, tx + 5, ya + 4], 0, 180, fill=C("roof"))
    # curved eaves (upturned corners)
    d.polygon([(8, 64), (cx, 24), (184, 64), (176, 72), (cx, 34), (16, 72)],
              fill=C("K"))
    d.polygon([(14, 64), (cx, 28), (178, 64), (172, 68), (cx, 36), (20, 68)],
              fill=C("roof"))
    d.line([(20, 66), (172, 66)], fill=C("roofd"))
    # gold ornaments on eave corners
    for x in (16, 176):
        d.ellipse([x - 4, 58, x + 4, 66], fill=C("gold"), outline=C("K"))
    star(d, cx, 44, 7, "gold")
    d.ellipse([cx - 3, 41, cx + 3, 47], fill=C("red"))
    return img


def stone_lantern():
    """24x48 stone lantern with glowing fire box."""
    img = new(24, 48)
    d = ImageDraw.Draw(img)
    r = rng(111)
    # base
    d.ellipse([5, 38, 19, 46], fill=C("K"))
    d.ellipse([6, 39, 18, 45], fill=C("stone"))
    speckle(d, 7, 40, 17, 44, ["stonel", "greyd"], r, 10)
    # shaft
    rect(d, 10, 30, 14, 39, "stone", outline="K", ow=1)
    d.line([(12, 30), (12, 39)], fill=C("greyd"))
    # fire box with warm window
    rect(d, 6, 18, 18, 30, "stone", outline="K", ow=2)
    speckle(d, 8, 20, 16, 28, ["stonel"], r, 8)
    d.ellipse([8, 20, 16, 28], fill=C("K"))
    d.ellipse([9, 21, 15, 27], fill=C("glow"))
    d.ellipse([10, 22, 14, 26], fill=C("paper"))
    # cap roof
    d.polygon([(12, 8), (20, 18), (4, 18)], fill=C("K"))
    d.polygon([(12, 11), (18, 17), (6, 17)], fill=C("stone"))
    d.line([(12, 11), (12, 17)], fill=C("greyd"))
    # jewel top
    d.ellipse([10, 4, 14, 9], fill=C("stone"), outline=C("K"))
    return img

# ---------------------------------------------------------------- water
def lake():
    """420x260 lake: sandy shore, gradient water, foam, lilies, sparkles."""
    img = new(420, 260)
    d = ImageDraw.Draw(img)
    r = rng(112)
    cx, cy, rx, ry = 210, 130, 204, 124
    # outer dark rim + sand ring
    d.ellipse([cx - rx, cy - ry, cx + rx, cy + ry], fill=C("K"))
    d.ellipse([cx - rx + 5, cy - ry + 5, cx + rx - 5, cy + ry - 5], fill=C("tan"))
    speckle(d, cx - rx + 8, cy - ry + 8, cx + rx - 8, cy + ry - 8,
            ["cream", "brown"], r, 200)
    # water with dithered depth gradient
    wx0, wy0, wx1, wy1 = cx - rx + 20, cy - ry + 20, cx + rx - 20, cy + ry - 20
    d.ellipse([wx0, wy0, wx1, wy1], fill=C("sky"))
    for y in range(wy0, wy1 + 1):
        t = (y - wy0) / max(1, (wy1 - wy0))
        for x in range(wx0, wx1 + 1):
            if ((x - cx) / (rx - 20)) ** 2 + ((y - cy) / (ry - 20)) ** 2 < 1:
                if r.random() < t * 0.85:
                    d.point((x, y), fill=C("blued"))
    # shore foam scallops
    for i in range(48):
        ang = 2 * math.pi * i / 48
        fx = int(cx + (rx - 24) * math.cos(ang))
        fy = int(cy + (ry - 24) * math.sin(ang))
        d.ellipse([fx - 5, fy - 2, fx + 5, fy + 3], fill=C("white"))
        d.ellipse([fx - 3, fy - 1, fx + 3, fy + 2], fill=C("sky"))
    # wave lines
    for _ in range(26):
        x = r.randint(wx0 + 10, wx1 - 20)
        y = r.randint(wy0 + 10, wy1 - 10)
        if ((x - cx) / (rx - 30)) ** 2 + ((y - cy) / (ry - 30)) ** 2 < 1:
            d.line([(x, y), (x + 10, y)], fill=C("white"))
            d.line([(x + 2, y + 2), (x + 8, y + 2)], fill=C("sky"))
    # lily pads + blossom
    for (x, y) in [(150, 150), (260, 110), (300, 170), (120, 100)]:
        d.ellipse([x - 8, y - 5, x + 8, y + 5], fill=C("K"))
        d.pieslice([x - 7, y - 4, x + 7, y + 4], 20, 340, fill=C("green"))
        d.line([(x, y), (x + 4, y - 2)], fill=C("greend"))
        if (x + y) % 2 == 0:
            for px_, py_ in [(x - 3, y - 7), (x + 2, y - 8), (x, y - 5)]:
                d.ellipse([px_ - 2, py_ - 2, px_ + 2, py_ + 2], fill=C("sakura"),
                          outline=C("sakurad"))
    # sparkles
    for _ in range(30):
        x = r.randint(wx0 + 6, wx1 - 6)
        y = r.randint(wy0 + 6, wy1 - 6)
        if ((x - cx) / (rx - 30)) ** 2 + ((y - cy) / (ry - 30)) ** 2 < 1:
            d.point((x, y), fill=C("white"))
            d.point((x + 1, y), fill=C("sky"))
    return img


def bridge():
    """160x48 arched wooden foot bridge with rails."""
    img = new(160, 48)
    d = ImageDraw.Draw(img)
    r = rng(113)
    # arc deck planks
    for x in range(4, 156, 10):
        arch = int(10 * (1 - abs(x - 80) / 80))
        top = 28 - arch
        rect(d, x, top, x + 9, 40 - arch // 2, "wood", outline="K", ow=1)
        d.line([(x + 1, top + 2), (x + 8, top + 2)], fill=C("woodd"))
        speckle(d, x + 1, top + 3, x + 8, 38, ["woodd"], r, 3)
    # rails
    for x in range(8, 152, 22):
        arch = int(10 * (1 - abs(x - 80) / 80))
        rect(d, x, 12 - arch, x + 4, 30 - arch, "woodd", outline="K", ow=1)
    for off in (0, 1):
        y_base = 12 + off * 5
        pts = [(x, y_base - int(10 * (1 - abs(x - 80) / 80))) for x in range(4, 157, 8)]
        d.line(pts, fill=C("K"), width=3)
        pts2 = [(x, y_base - int(10 * (1 - abs(x - 80) / 80))) for x in range(4, 157, 8)]
        d.line(pts2, fill=C("wood"), width=1)
    # rope ties
    for x in range(8, 152, 22):
        arch = int(10 * (1 - abs(x - 80) / 80))
        d.ellipse([x, 12 - arch, x + 4, 16 - arch], fill=C("gold"), outline=C("K"))
    return img


def dock():
    """96x32 wooden dock with posts and rope."""
    img = new(96, 32)
    d = ImageDraw.Draw(img)
    r = rng(114)
    # posts
    for x in (6, 84):
        rect(d, x, 18, x + 7, 31, "woodd", outline="K", ow=1)
        d.ellipse([x, 16, x + 7, 22], fill=C("wood"), outline=C("K"))
    # deck planks
    rect(d, 2, 4, 94, 22, "wood", outline="K", ow=2)
    for x in range(2, 94, 13):
        d.line([(x, 5), (x, 21)], fill=C("woodd"))
        d.point((x + 3, 9), fill=C("char"))
        d.point((x + 3, 17), fill=C("char"))
    speckle(d, 4, 6, 92, 20, ["woodd", "tan"], r, 40)
    # rope along edge
    d.line([(2, 23), (94, 23)], fill=C("tan"), width=2)
    for x in range(6, 94, 12):
        d.line([(x, 21), (x, 25)], fill=C("brown"), width=1)
    return img


def town_gate():
    """48x96 stone gate pillars with wooden beam and lantern."""
    img = new(48, 96)
    d = ImageDraw.Draw(img)
    r = rng(115)
    # pillars
    for x in (4, 34):
        bricks(d, x, 30, x + 10, 90, 6, "stone", "greyd", r)
        rect(d, x, 30, x + 10, 90, None, outline="K", ow=2)
        # cap stone
        d.polygon([(x - 3, 30), (x + 13, 30), (x + 5, 20)], fill=C("K"))
        d.polygon([(x - 1, 29), (x + 11, 29), (x + 5, 22)], fill=C("stonel"))
        # base
        rect(d, x - 2, 88, x + 12, 94, "greyd", outline="K", ow=1)
    # wooden beam
    rect(d, 0, 8, 48, 20, "wood", outline="K", ow=2)
    planks_h(d, 2, 10, 46, 18, "wood", "woodd", r)
    rect(d, 18, 10, 30, 18, "char", outline="gold", ow=1)
    star(d, 24, 14, 4, "gold")
    # hanging lantern from beam
    d.line([(24, 20), (24, 26)], fill=C("K"), width=2)
    d.ellipse([18, 26, 30, 38], fill=C("K"))
    d.ellipse([19, 27, 29, 37], fill=C("paper"))
    d.ellipse([21, 29, 27, 35], fill=C("glow"))
    return img

# ---------------------------------------------------------------- props
def power_pole():
    """32x96 power pole with crossarm, insulators, wire nubs."""
    img = new(32, 96)
    d = ImageDraw.Draw(img)
    r = rng(116)
    # pole with grain
    rect(d, 13, 6, 19, 94, "woodd", outline="K", ow=1)
    planks_v(d, 14, 8, 18, 92, "woodd", "char", r, pw=2)
    rect(d, 15, 8, 16, 92, "wood")
    # crossarm
    rect(d, 4, 14, 28, 20, "woodd", outline="K", ow=1)
    d.line([(5, 17), (27, 17)], fill=C("wood"))
    # insulators
    for x in (8, 24):
        d.ellipse([x - 3, 10, x + 3, 16], fill=C("K"))
        d.ellipse([x - 2, 11, x + 2, 15], fill=C("white"))
        d.line([(x, 16), (x, 20)], fill=C("K"))
    # wire nubs on the sides (wires drawn by town_wire layer in-game)
    for y in (15, 18):
        d.ellipse([1, y, 5, y + 4], fill=C("K"))
        d.ellipse([27, y, 31, y + 4], fill=C("K"))
    # base
    d.polygon([(11, 94), (21, 94), (24, 96), (8, 96)], fill=C("K"))
    # metal bands
    for y in (34, 62):
        rect(d, 13, y, 19, y + 3, "greyd", outline="K", ow=1)
    return img


def sakura_tree():
    """64x80 sakura: gnarled trunk, layered blossom canopy, petals."""
    img = new(64, 80)
    d = ImageDraw.Draw(img)
    r = rng(117)
    # trunk with roots
    d.polygon([(28, 78), (36, 78), (34, 50), (30, 50)], fill=C("K"))
    d.polygon([(29, 77), (35, 77), (33, 51), (31, 51)], fill=C("woodd"))
    d.line([(32, 52), (32, 76)], fill=C("wood"))
    for bx, sgn in [(26, -1), (38, 1)]:
        d.polygon([(30, 78), (34, 78), (bx, 70)], fill=C("K"))
    # branches
    for (x0, y0, x1, y1) in [(32, 52, 20, 38), (32, 52, 44, 38), (32, 50, 32, 34)]:
        d.line([(x0, y0), (x1, y1)], fill=C("K"), width=4)
        d.line([(x0, y0), (x1, y1)], fill=C("woodd"), width=2)
    # canopy blobs: dark outline, dithered pink fill
    blobs = [(32, 24, 19), (17, 32, 12), (47, 32, 12), (32, 38, 13), (25, 18, 10),
             (40, 20, 10)]
    for (x, y, rad) in blobs:
        d.ellipse([x - rad, y - rad, x + rad, y + rad], fill=C("K"))
    for (x, y, rad) in blobs:
        for py in range(y - rad + 1, y + rad):
            t = (py - (y - rad)) / (2 * rad)
            for px in range(x - rad + 1, x + rad):
                if ((px - x) / rad) ** 2 + ((py - y) / rad) ** 2 < 0.92:
                    d.point((px, py), fill=C("sakurad" if r.random() < t * 0.7
                                            else "sakura"))
    # blossom clusters (light)
    for _ in range(26):
        x = r.randint(14, 50)
        y = r.randint(8, 44)
        if ((x - 32) / 22) ** 2 + ((y - 28) / 20) ** 2 < 1:
            d.ellipse([x - 2, y - 2, x + 2, y + 2], fill=C("white"))
            d.point((x, y), fill=C("sakura"))
    # drifting petals
    for (x, y) in [(12, 58), (52, 60), (44, 68), (20, 66)]:
        d.ellipse([x - 2, y - 1, x + 2, y + 1], fill=C("sakura"), outline=C("sakurad"))
    return img


def stone_path():
    """64x64 flagstone path with mossy gaps."""
    img = new(64, 64)
    d = ImageDraw.Draw(img)
    r = rng(118)
    # mossy base
    rect(d, 0, 0, 63, 63, "greend")
    speckle(d, 0, 0, 63, 63, ["green"], r, 120)
    # flagstones
    stones = [(2, 2, 20, 18), (24, 4, 42, 20), (46, 2, 62, 18),
              (4, 22, 22, 40), (26, 24, 44, 42), (48, 22, 62, 40),
              (2, 44, 20, 62), (24, 46, 42, 62), (46, 44, 62, 62)]
    for (x0, y0, x1, y1) in stones:
        d.rounded_rectangle([x0, y0, x1, y1], radius=4, fill=C("K"))
        d.rounded_rectangle([x0 + 2, y0 + 2, x1 - 2, y1 - 2], radius=3,
                           fill=C("stone"))
        speckle(d, x0 + 3, y0 + 3, x1 - 3, y1 - 3, ["stonel", "greyd"], r, 12)
        # top-left highlight
        d.line([(x0 + 3, y0 + 3), (x1 - 4, y0 + 3)], fill=C("stonel"))
    return img


def plaza_tile():
    """64x64 plaza tile with medallion motif."""
    img = new(64, 64)
    d = ImageDraw.Draw(img)
    r = rng(119)
    rect(d, 0, 0, 63, 63, "plasd")
    # large tiles
    for ty in range(0, 64, 32):
        for tx in range(0, 64, 32):
            rect(d, tx + 1, ty + 1, tx + 30, ty + 30, "plas", outline="K", ow=1)
            speckle(d, tx + 3, ty + 3, tx + 28, ty + 28, ["plasd"], r, 10)
    # center medallion
    d.ellipse([18, 18, 46, 46], fill=C("K"))
    d.ellipse([20, 20, 44, 44], fill=C("roof"))
    d.ellipse([24, 24, 40, 40], fill=C("plas"))
    star(d, 32, 32, 8, "roof")
    star(d, 32, 32, 4, "gold")
    # corner studs
    for (x, y) in [(6, 6), (58, 6), (6, 58), (58, 58)]:
        d.ellipse([x - 3, y - 3, x + 3, y + 3], fill=C("roofd"), outline=C("K"))
    return img


BUILDINGS = {
    "house_a": (house_a, "assets/town/house_a.png"),
    "house_b": (house_b, "assets/town/house_b.png"),
    "station_hall": (station_hall, "assets/town/station_hall.png"),
    "clock_tower": (clock_tower, "assets/town/clock_tower.png"),
    "platform": (platform, "assets/town/platform.png"),
    "stall": (stall, "assets/town/stall.png"),
    "bulletin": (bulletin, "assets/town/bulletin.png"),
    "vending": (vending, "assets/town/vending.png"),
    "torii": (torii, "assets/town/torii.png"),
    "shrine_hall": (shrine_hall, "assets/town/shrine_hall.png"),
    "stone_lantern": (stone_lantern, "assets/town/stone_lantern.png"),
    "lake": (lake, "assets/town/lake.png"),
    "bridge": (bridge, "assets/town/bridge.png"),
    "dock": (dock, "assets/town/dock.png"),
    "town_gate": (town_gate, "assets/town/town_gate.png"),
    "power_pole": (power_pole, "assets/town/power_pole.png"),
    "sakura_tree": (sakura_tree, "assets/town/sakura_tree.png"),
    "stone_path": (stone_path, "assets/town/stone_path.png"),
    "plaza_tile": (plaza_tile, "assets/town/plaza_tile.png"),
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    os.makedirs(args.out, exist_ok=True)
    manifest = []
    for name, (fn, rel) in BUILDINGS.items():
        img = fn()
        img.save(os.path.join(args.out, name + ".png"))
        manifest.append({"path": rel, "width": img.size[0], "height": img.size[1]})
    with open(os.path.join(args.out, "town_manifest.json"), "w") as fh:
        json.dump(manifest, fh, indent=1)
    print("generated %d town sprites -> %s" % (len(manifest), args.out))


if __name__ == "__main__":
    main()
