#!/usr/bin/env python3
"""Synthesize original CC0 town music + ambience for Paloria (AT-E).

All sounds generated with numpy: no third-party samples.
Provenance: GENERATED by project tool, license CC0-1.0.
Music: seamless OGG loops via ffmpeg. Ambience: seamless OGG loops.

Cues: music.town.day/dusk/night/rain, music.shrine.story, music.outskirts.danger
Beds: amb.wind/birds/cicadas/crickets/rain/water/train

Usage:
    python3 tools/synthesize_town_audio.py --out /tmp/paloria_town_audio
"""
import argparse
import os
import subprocess
import wave

import numpy as np

SR = 22050


def _write_wav(path, samples):
    samples = np.clip(samples, -1.0, 1.0)
    pcm = (samples * 32767).astype(np.int16)
    with wave.open(path, "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(SR)
        w.writeframes(pcm.tobytes())


def _to_ogg(wav_path, ogg_path):
    subprocess.run(["ffmpeg", "-y", "-loglevel", "error", "-i", wav_path,
                    "-c:a", "libvorbis", "-q:a", "4", ogg_path], check=True)


def _midi(m):
    return 440.0 * 2 ** ((m - 69) / 12)


def _tone(freq, seconds, wave="sine", vol=0.5, attack=0.01, decay=3.0):
    n = int(SR * seconds)
    t = np.arange(n) / SR
    ph = 2 * np.pi * freq * t
    if wave == "sine":
        s = np.sin(ph)
    elif wave == "square":
        s = np.sign(np.sin(ph)) * 0.6
    elif wave == "triangle":
        s = 2 * np.abs(2 * ((ph / (2 * np.pi)) % 1) - 1) - 1
    else:
        s = np.sin(ph)
    env = np.minimum(1.0, np.arange(n) / (attack * SR)) * np.exp(-decay * t / seconds)
    return s * env * vol


def _noise(seconds, vol=0.4, alpha=0.15):
    n = int(SR * seconds)
    w = np.random.default_rng(7).standard_normal(n)
    out = np.zeros(n)
    last = 0.0
    for i in range(n):
        last = last + alpha * (w[i] - last)
        out[i] = last
    out = out / (np.max(np.abs(out)) + 1e-6)
    return out * vol


def _place(out, sig, at_seconds):
    st = int(at_seconds * SR)
    if st >= len(out):
        return
    end = min(len(out), st + len(sig))
    out[st:end] += sig[: end - st]


def _seamless(x, fade=0.5):
    n = len(x)
    f = int(SR * fade)
    head = x[:f].copy()
    x[:f] = x[:f] * np.linspace(0, 1, f) + x[n - f:] * np.linspace(1, 0, f)
    x[n - f:] = x[n - f:] * np.linspace(0, 1, f) + head * np.linspace(1, 0, f)
    return x


def _normalize(x, peak=0.85):
    m = np.max(np.abs(x))
    return x / m * peak if m > 0 else x


def compose(bpm, bars, roots, chords, bass_wave="triangle", bass_vol=0.32,
            lead_wave="square", lead_vol=0.10, lead_oct=12, hats=True,
            melody=None, pad=False):
    """Generic chiptune loop builder. roots/chords: per-bar midi lists."""
    beat = 60.0 / bpm
    bar = beat * 4
    total = bar * bars
    out = np.zeros(int(SR * total))
    t = 0.0
    for b in range(bars):
        root = roots[b % len(roots)]
        chord = chords[b % len(chords)]
        for e in range(8):
            _place(out, _tone(_midi(root), beat / 2 * 0.95, bass_wave, bass_vol),
                   t + e * beat / 2)
        arp = chord + [chord[2] + 12]
        for s in range(16):
            _place(out, _tone(_midi(arp[s % 4] + lead_oct), beat / 4 * 0.9, lead_wave, lead_vol),
                   t + s * beat / 4)
        if pad:
            for note in chord:
                _place(out, _tone(_midi(note), bar, "sine", 0.05, attack=0.8, decay=0.5), t)
        if hats:
            for s in range(8):
                _place(out, _noise(0.03, vol=0.08, alpha=0.6), t + s * beat / 2 + beat / 4)
        if melody:
            for start_beat, midi_note, dur_beats in melody[b % len(melody)]:
                _place(out, _tone(_midi(midi_note), dur_beats * beat * 0.95, "sine", 0.16,
                                 attack=0.05, decay=1.5), t + start_beat * beat)
        t += bar
    return _normalize(_seamless(out))


def music_town_day():
    return compose(120, 8, [48, 43, 45, 41],
                   [[60, 64, 67], [59, 62, 67], [60, 64, 69], [60, 65, 69]])


def music_town_dusk():
    return compose(90, 8, [41, 48, 38, 46],
                   [[60, 65, 69], [60, 64, 67], [62, 65, 69], [58, 62, 65]],
                   bass_vol=0.28, lead_wave="triangle", lead_vol=0.12, hats=False)


def music_town_night():
    mel = [[(0, 69, 2), (2.5, 67, 1)], [(0, 65, 3)], [(0, 67, 2), (2.5, 64, 1)], [(0, 62, 4)]]
    return compose(70, 8, [45, 41, 48, 43],
                   [[57, 60, 64], [53, 57, 60], [55, 60, 64], [55, 59, 62]],
                   bass_vol=0.22, lead_vol=0.0, hats=False, melody=mel, pad=True)


def music_town_rain():
    base = compose(80, 8, [50, 46, 48, 43],
                   [[62, 65, 69], [58, 62, 65], [60, 64, 67], [59, 62, 67]],
                   bass_vol=0.24, lead_wave="sine", lead_vol=0.10, hats=False, pad=True)
    rain = _noise(len(base) / SR, vol=0.05, alpha=0.5)
    return _normalize(_seamless(base + rain[: len(base)]))


def music_shrine_story():
    mel = [[(0, 64, 3), (3, 67, 1)], [(0, 65, 4)], [(0, 67, 2), (2, 71, 2)], [(0, 69, 4)],
           [(0, 67, 3), (3, 64, 1)], [(0, 65, 4)], [(0, 62, 2), (2, 64, 2)], [(0, 60, 4)]]
    return compose(60, 8, [45, 41, 48, 43, 45, 41, 38, 43],
                   [[57, 60, 64], [53, 57, 60], [55, 60, 64], [55, 59, 62],
                    [57, 60, 64], [53, 57, 60], [50, 53, 57], [55, 59, 62]],
                   bass_vol=0.20, lead_vol=0.0, hats=False, melody=mel, pad=True)


def music_outskirts_danger():
    return compose(140, 8, [38, 38, 46, 45],
                   [[62, 65, 69], [62, 65, 69], [58, 62, 65], [57, 60, 64]],
                   bass_wave="square", bass_vol=0.22, lead_wave="square",
                   lead_vol=0.08, lead_oct=0, hats=True)


# ------------------------------------------------------------- ambience
def amb_wind():
    n = 10.0
    base = _noise(n, vol=0.30, alpha=0.08)
    lfo = 0.5 + 0.5 * np.sin(2 * np.pi * np.arange(len(base)) / SR * 0.15)
    return _normalize(_seamless(base * (0.4 + 0.6 * lfo)), 0.6)


def amb_birds():
    rng = np.random.default_rng(21)
    out = _noise(12.0, vol=0.06, alpha=0.3)
    t = 0.5
    while t < 11.0:
        f0 = rng.uniform(2800, 4200)
        chirp = _tone(f0, 0.12, "sine", 0.20, attack=0.02, decay=8.0)
        chirp += _tone(f0 * 1.3, 0.12, "sine", 0.12, attack=0.02, decay=8.0)
        _place(out, chirp, t)
        if rng.random() < 0.5:
            _place(out, chirp, t + 0.18)
        t += rng.uniform(0.8, 2.4)
    return _normalize(_seamless(out), 0.6)


def amb_cicadas():
    n = int(SR * 10.0)
    t = np.arange(n) / SR
    buzz = np.sin(2 * np.pi * 5200 * t) * (0.5 + 0.5 * np.sign(np.sin(2 * np.pi * 28 * t)))
    swell = 0.5 + 0.5 * np.sin(2 * np.pi * t * 0.2)
    return _normalize(_seamless(buzz * swell * 0.25), 0.6)


def amb_crickets():
    rng = np.random.default_rng(33)
    out = np.zeros(int(SR * 10.0))
    t = 0.3
    while t < 9.5:
        for k in range(3):
            _place(out, _tone(4400, 0.05, "sine", 0.15, attack=0.01, decay=10.0), t + k * 0.09)
        t += rng.uniform(0.5, 1.1)
    return _normalize(_seamless(out), 0.6)


def amb_rain():
    return _normalize(_seamless(_noise(10.0, vol=0.35, alpha=0.5)), 0.6)


def amb_water():
    n = 10.0
    base = _noise(n, vol=0.25, alpha=0.25)
    lfo = 0.5 + 0.5 * np.sin(2 * np.pi * np.arange(len(base)) / SR * 0.4)
    return _normalize(_seamless(base * (0.3 + 0.7 * lfo)), 0.6)


def amb_train():
    n = int(SR * 12.0)
    t = np.arange(n) / SR
    rumble = _noise(12.0, vol=0.20, alpha=0.05)
    swell = np.clip(np.sin(np.pi * t / 12.0), 0, 1) ** 2
    horn = _tone(233, 1.2, "sine", 0.10, attack=0.3, decay=0.8)
    horn += _tone(175, 1.2, "sine", 0.10, attack=0.3, decay=0.8)
    out = rumble * (0.3 + 0.7 * swell)
    _place(out, horn, 4.0)
    return _normalize(_seamless(out), 0.6)


TRACKS = {
    "music_town_day": music_town_day,
    "music_town_dusk": music_town_dusk,
    "music_town_night": music_town_night,
    "music_town_rain": music_town_rain,
    "music_shrine_story": music_shrine_story,
    "music_outskirts_danger": music_outskirts_danger,
    "amb_wind": amb_wind,
    "amb_birds": amb_birds,
    "amb_cicadas": amb_cicadas,
    "amb_crickets": amb_crickets,
    "amb_rain": amb_rain,
    "amb_water": amb_water,
    "amb_train": amb_train,
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    os.makedirs(args.out, exist_ok=True)
    for name, fn in TRACKS.items():
        wav = os.path.join(args.out, name + ".wav")
        ogg = os.path.join(args.out, name + ".ogg")
        print("synth", name, flush=True)
        _write_wav(wav, fn())
        _to_ogg(wav, ogg)
        os.remove(wav)
    print("done ->", args.out)


if __name__ == "__main__":
    main()
