#!/usr/bin/env python3
"""Synthesize original CC0 audio for Paloria 2D (U4.2).

All sounds are generated by this script with numpy: no third-party samples.
Provenance: GENERATED by project tool, license CC0-1.0.
SFX: 16-bit mono WAV 22050 Hz. Music: seamless OGG loop via ffmpeg.

Usage:
    python3 tools/synthesize_audio.py --out /tmp/paloria_audio
"""
import argparse
import os
import subprocess
import wave

import numpy as np

SR = 22050


def _write_wav(path, samples):
    samples = np.clip(samples, -1.0, 1.0)
    pcm = (samples * 32767).astype(np.int16)
    with wave.open(path, "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(SR)
        w.writeframes(pcm.tobytes())


def _tone(freq, seconds, wave_type="sine", volume=0.7, slide_to=None):
    n = int(SR * seconds)
    t = np.arange(n) / SR
    if slide_to is not None:
        freqs = np.linspace(freq, slide_to, n)
        phase = 2 * np.pi * np.cumsum(freqs) / SR
    else:
        phase = 2 * np.pi * freq * t
    if wave_type == "sine":
        s = np.sin(phase)
    elif wave_type == "square":
        s = np.sign(np.sin(phase))
    elif wave_type == "triangle":
        s = 2 * np.abs(2 * (phase / (2 * np.pi) % 1) - 1) - 1
    else:
        s = np.sin(phase)
    env = np.minimum(1.0, np.arange(n) / (0.01 * SR)) * np.exp(-3.0 * t / seconds)
    return s * env * volume


def _noise(seconds, volume=0.5, lowpass=0.2):
    n = int(SR * seconds)
    s = np.random.default_rng(7).standard_normal(n)
    kernel = int(SR * lowpass / 100)
    if kernel > 1:
        s = np.convolve(s, np.ones(kernel) / kernel, mode="same")
    t = np.arange(n) / SR
    env = np.exp(-4.0 * t / seconds)
    return s * env * volume


def _seq(parts):
    return np.concatenate(parts)


def sfx_coin():
    return _seq([_tone(1318.5, 0.08), _tone(1975.5, 0.18)])


def sfx_jump():
    return _tone(300, 0.22, slide_to=720, volume=0.5)


def sfx_hit():
    n = int(SR * 0.25)
    thump = _tone(120, 0.25, slide_to=60, volume=0.8)
    nz = _noise(0.18, volume=0.5, lowpass=0.05)
    out = thump.copy()
    out[: len(nz)] += nz
    return out


def sfx_sword():
    n = int(SR * 0.22)
    rng = np.random.default_rng(3)
    s = rng.standard_normal(n)
    t = np.arange(n) / SR
    sweep = np.exp(-6.0 * t)
    # downward spectral sweep approximated by amplitude + pitch feel
    return s * sweep * 0.5 + _tone(2400, 0.22, slide_to=700, volume=0.25)


def sfx_fireball():
    whoosh = _noise(0.4, volume=0.55, lowpass=0.1)
    return whoosh + _tone(500, 0.4, slide_to=150, volume=0.35)


def sfx_alert():
    return _seq([_tone(880, 0.12, "square", 0.35), _tone(0.001, 0.06),
                 _tone(880, 0.12, "square", 0.35), _tone(0.001, 0.06),
                 _tone(1174.7, 0.2, "square", 0.35)])


def sfx_powerup():
    notes = [523.25, 659.25, 783.99, 1046.5]
    return _seq([_tone(f, 0.11, "triangle", 0.6) for f in notes])


def sfx_success():
    chord = sum(_tone(f, 0.7, "sine", 0.3) for f in (523.25, 659.25, 783.99))
    arp = _seq([_tone(f, 0.12, "triangle", 0.5) for f in (523.25, 659.25, 783.99, 1046.5)])
    out = np.zeros(max(len(chord), len(arp)))
    out[: len(chord)] += chord
    out[: len(arp)] += arp * 0.7
    return out


NOTE_NAMES = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"]


def _midi_freq(m):
    return 440.0 * 2 ** ((m - 69) / 12)


def music_adventure():
    """Cheerful 16-bar chiptune loop, 132 BPM, seamless."""
    bpm = 132
    beat = 60.0 / bpm
    bar = beat * 4
    # I–V–vi–IV in C major, two bars each
    roots = [48, 43, 45, 41]  # C2 G1 A1 F1 (midi)
    chords = [[60, 64, 67], [59, 62, 67], [60, 64, 69], [60, 65, 69]]
    total = bar * 16
    n = int(SR * total)
    out = np.zeros(n)
    t_bar = 0.0
    for rep in range(2):
        for b in range(4):
            root = roots[b]
            chord = chords[b]
            # bass: root eighth notes (triangle)
            for e in range(8):
                s = _tone(_midi_freq(root), beat / 2 * 0.95, "triangle", 0.35)
                st = int((t_bar + e * beat / 2) * SR)
                out[st: st + len(s)] += s[: max(0, n - st)]
            # lead: arpeggio sixteenths (square, soft)
            arp_notes = chord + [chord[2] + 12]
            for s_idx in range(16):
                f = _midi_freq(arp_notes[s_idx % 4] + 12)
                s = _tone(f, beat / 4 * 0.9, "square", 0.12)
                st = int((t_bar + s_idx * beat / 4) * SR)
                out[st: st + len(s)] += s[: max(0, n - st)]
            # hats: noise ticks
            for s_idx in range(8):
                nz = _noise(0.03, volume=0.10, lowpass=0.01)
                st = int((t_bar + s_idx * beat / 2 + beat / 4) * SR)
                out[st: st + len(nz)] += nz[: max(0, n - st)]
            t_bar += bar
    # gentle master fade edges are NOT applied (seamless loop); normalize
    peak = np.max(np.abs(out))
    if peak > 0:
        out = out / peak * 0.85
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    os.makedirs(args.out, exist_ok=True)
    sfx = {
        "coin": sfx_coin, "jump": sfx_jump, "hit": sfx_hit, "sword": sfx_sword,
        "fireball": sfx_fireball, "alert": sfx_alert, "powerup": sfx_powerup,
        "success": sfx_success,
    }
    manifest = []
    for name, fn in sfx.items():
        path = os.path.join(args.out, name + ".wav")
        _write_wav(path, fn())
        manifest.append({"path": "assets/sfx/%s.wav" % name, "file": name + ".wav"})
        print("sfx", name)
    music_path = os.path.join(args.out, "adventure_begin.wav")
    _write_wav(music_path, music_adventure())
    ogg_path = os.path.join(args.out, "adventure_begin.ogg")
    subprocess.run(["ffmpeg", "-y", "-loglevel", "error", "-i", music_path,
                    "-c:a", "libvorbis", "-q:a", "4", ogg_path], check=True)
    manifest.append({"path": "assets/music/adventure_begin.ogg", "file": "adventure_begin.ogg"})
    print("music adventure_begin")
    import json
    with open(os.path.join(args.out, "audio_manifest.json"), "w") as fh:
        json.dump(manifest, fh, indent=1)


if __name__ == "__main__":
    main()
