#!/usr/bin/env python3
"""Synthesize original CC0 town music + ambience for Paloria (AT-E, refreshed).

Music direction (per user feedback 2026-10-08): peaceful, chill lo-fi.
Warm Rhodes-style electric piano chords, soft sub bass, sparse pentatonic
koto-like pluck melodies, dreamy pads, gentle echo, subtle vinyl crackle.
No square waves, no hats, no driving percussion; 60-78 BPM.

All sounds generated with numpy: no third-party samples.
Provenance: GENERATED by project tool, license CC0-1.0.
Music: seamless OGG loops via ffmpeg. Ambience: seamless OGG loops.

Cues: music.town.day/dusk/night/rain, music.shrine.story, music.outskirts.danger
Beds: amb.wind/birds/cicadas/crickets/rain/water/train

Usage:
    python3 tools/synthesize_town_audio.py --out /tmp/paloria_town_audio
"""
import argparse
import os
import subprocess
import wave

import numpy as np

SR = 22050


def _write_wav(path, samples):
    samples = np.clip(samples, -1.0, 1.0)
    pcm = (samples * 32767).astype(np.int16)
    with wave.open(path, "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(SR)
        w.writeframes(pcm.tobytes())


def _to_ogg(wav_path, ogg_path):
    subprocess.run(["ffmpeg", "-y", "-loglevel", "error", "-i", wav_path,
                    "-c:a", "libvorbis", "-q:a", "4", ogg_path], check=True)


def _midi(m):
    return 440.0 * 2 ** ((m - 69) / 12)


NOTE_OFF = {"C": 0, "D": 2, "E": 4, "F": 5, "G": 7, "A": 9, "B": 11}


def N(name):
    """Note name like 'F3' or 'Bb2' -> midi."""
    name = name.strip()
    acc = 0
    if len(name) > 2 and name[1] in ("#", "b"):
        acc = 1 if name[1] == "#" else -1
        letter, octave = name[0], int(name[2:])
    else:
        letter, octave = name[0], int(name[1:])
    return 12 * (octave + 1) + NOTE_OFF[letter] + acc


# ------------------------------------------------------------ instruments
def _ep(freq, seconds, vol=0.30, decay=2.2):
    """Rhodes-ish electric piano: soft harmonics + tremolo."""
    n = int(SR * seconds)
    t = np.arange(n) / SR
    env = np.minimum(1.0, t / 0.008) * np.exp(-t / decay)
    trem = 1.0 - 0.22 * (0.5 + 0.5 * np.sin(2 * np.pi * 4.5 * t))
    s = (np.sin(2 * np.pi * freq * t)
         + 0.28 * np.sin(2 * np.pi * 2 * freq * t) * np.exp(-t / (decay * 0.5))
         + 0.10 * np.sin(2 * np.pi * 3 * freq * t) * np.exp(-t / (decay * 0.3)))
    return s * env * trem * vol


def _pluck(freq, seconds, vol=0.22, decay=1.1):
    """Koto-like pluck: bright attack, quick warm decay."""
    n = int(SR * seconds)
    t = np.arange(n) / SR
    env = np.minimum(1.0, t / 0.004) * np.exp(-t / decay)
    s = (np.sin(2 * np.pi * freq * t)
         + 0.45 * np.sin(2 * np.pi * 2 * freq * t) * np.exp(-t / 0.35)
         + 0.20 * np.sin(2 * np.pi * 3 * freq * t) * np.exp(-t / 0.18))
    return s * env * vol


def _pad_note(freq, seconds, vol=0.10):
    n = int(SR * seconds)
    t = np.arange(n) / SR
    attack = min(1.8, seconds * 0.4)
    env = np.minimum(1.0, t / attack) * np.minimum(1.0, (seconds - t) / 0.8)
    s = (np.sin(2 * np.pi * freq * t)
         + 0.6 * np.sin(2 * np.pi * freq * 1.0018 * t)
         + 0.25 * np.sin(2 * np.pi * 2 * freq * t))
    return s * env * vol


def _sub(freq, seconds, vol=0.22):
    n = int(SR * seconds)
    t = np.arange(n) / SR
    env = np.minimum(1.0, t / 0.05) * np.minimum(1.0, (seconds - t) / 0.4)
    return np.sin(2 * np.pi * freq * t) * env * vol


def _noise(seconds, vol=0.4, alpha=0.15, seed=7):
    n = int(SR * seconds)
    w = np.random.default_rng(seed).standard_normal(n)
    out = np.zeros(n)
    last = 0.0
    for i in range(n):
        last = last + alpha * (w[i] - last)
        out[i] = last
    out = out / (np.max(np.abs(out)) + 1e-6)
    return out * vol


def _crackle(seconds, vol=0.012, seed=99):
    """Sparse vinyl crackle."""
    rng = np.random.default_rng(seed)
    n = int(SR * seconds)
    out = np.zeros(n)
    idx = rng.choice(n, size=n // 400, replace=False)
    out[idx] = rng.uniform(-1, 1, size=len(idx))
    return out * vol


def _place(out, sig, at_seconds):
    st = int(at_seconds * SR)
    if st >= len(out):
        return
    end = min(len(out), st + len(sig))
    out[st:end] += sig[: end - st]


def _echo(x, beat, vol=0.16, repeats=3):
    """Dotted-eighth style feedback echo."""
    d = int(SR * beat * 0.75)
    y = x.copy()
    wet = np.zeros_like(x)
    for k in range(1, repeats + 1):
        amp = vol * (0.55 ** (k - 1))
        wet[d * k:] += x[: len(x) - d * k] * amp
    return y + wet


def _seamless(x, fade=0.8):
    n = len(x)
    f = int(SR * fade)
    head = x[:f].copy()
    x[:f] = x[:f] * np.linspace(0, 1, f) + x[n - f:] * np.linspace(1, 0, f)
    x[n - f:] = x[n - f:] * np.linspace(0, 1, f) + head * np.linspace(1, 0, f)
    return x


def _normalize(x, peak=0.82):
    m = np.max(np.abs(x))
    return x / m * peak if m > 0 else x


# ------------------------------------------------------------ chill songs
def compose_chill(bpm, bars, prog, melody, ep_vol=0.30, pad_vol=0.05,
                  pluck_vol=0.20, sub_vol=0.20, seed=7, echo_vol=0.16,
                  crackle_vol=0.012, ep_pattern=(0, 2.5)):
    """Lo-fi loop builder.

    prog: list of (bass_note, [chord midis]) per bar.
    melody: list per bar of (start_beat, note_name, dur_beats).
    """
    beat = 60.0 / bpm
    bar = beat * 4
    total = bar * bars
    out = np.zeros(int(SR * total))
    t = 0.0
    for b in range(bars):
        bass_name, chord = prog[b % len(prog)]
        # pad: whole-bar warm wash
        for m in chord:
            _place(out, _pad_note(_midi(m), bar, pad_vol), t)
        # EP stabs (laid-back pattern)
        for sb in ep_pattern:
            for m in chord:
                _place(out, _ep(_midi(m), beat * 2.2, ep_vol / max(1, len(chord))),
                       t + sb * beat)
        # sub bass root
        _place(out, _sub(_midi(N(bass_name)), bar, sub_vol), t)
        # pluck melody
        for start_beat, note_name, dur_beats in melody[b % len(melody)]:
            _place(out, _pluck(_midi(N(note_name)), dur_beats * beat + 0.6,
                               pluck_vol), t + start_beat * beat)
        t += bar
    out = _echo(out, beat, vol=echo_vol)
    out = out + _crackle(total, vol=crackle_vol, seed=seed)
    return _normalize(_seamless(out))


def _penta_melody(rng, bars, scale, density=0.55, octv=5):
    """Sparse pentatonic melody with rests; deterministic."""
    mel = []
    for _ in range(bars):
        bar = []
        beat = 0.0
        while beat < 3.5:
            if rng.random() < density:
                note = rng.choice(scale) + str(octv + (1 if rng.random() < 0.15 else 0))
                dur = rng.choice([1.0, 1.5, 2.0])
                bar.append((beat, note, dur))
                beat += dur + rng.choice([0.0, 0.5])
            else:
                beat += rng.choice([0.5, 1.0])
        mel.append(bar)
    return mel


def music_town_day():
    # warm sunny lo-fi: Fmaj7 - Am7 - Dm7 - Bbmaj7
    prog = [
        ("F2", [N("F3"), N("A3"), N("C4"), N("E4")]),
        ("A2", [N("A3"), N("C4"), N("E4"), N("G3")]),
        ("D3", [N("D3"), N("F3"), N("A3"), N("C4")]),
        ("Bb2", [N("Bb2"), N("D3"), N("F3"), N("A3")]),
    ]
    rng = np.random.default_rng(11)
    mel = _penta_melody(rng, 8, ["F", "G", "A", "C", "D"], density=0.6)
    return compose_chill(72, 8, prog, mel, seed=11)


def music_town_dusk():
    # mellow amber: Cmaj7 - Am7 - Fmaj7 - G6
    prog = [
        ("C3", [N("C3"), N("E3"), N("G3"), N("B3")]),
        ("A2", [N("A2"), N("C3"), N("E3"), N("G3")]),
        ("F2", [N("F2"), N("A2"), N("C3"), N("E3")]),
        ("G2", [N("G2"), N("B2"), N("D3"), N("E3")]),
    ]
    rng = np.random.default_rng(22)
    mel = _penta_melody(rng, 8, ["C", "D", "E", "G", "A"], density=0.5)
    return compose_chill(66, 8, prog, mel, ep_vol=0.26, seed=22,
                         ep_pattern=(0, 2.0, 3.0))


def music_town_night():
    # dreamy sparse: Am9 - Fmaj9 - Cmaj9 - G6
    prog = [
        ("A2", [N("A2"), N("C3"), N("E3"), N("B3")]),
        ("F2", [N("F2"), N("A2"), N("C3"), N("G3")]),
        ("C3", [N("C3"), N("E3"), N("G3"), N("D4")]),
        ("G2", [N("G2"), N("B2"), N("D3"), N("E3")]),
    ]
    rng = np.random.default_rng(33)
    mel = _penta_melody(rng, 8, ["A", "C", "D", "E", "G"], density=0.38, octv=5)
    return compose_chill(60, 8, prog, mel, ep_vol=0.22, pad_vol=0.06,
                         pluck_vol=0.16, seed=33, echo_vol=0.20,
                         ep_pattern=(0, 3.0))


def music_town_rain():
    # soft rain-day: Dm9 - Bbmaj7 - Fmaj7 - Cadd9, rain bed underneath
    prog = [
        ("D3", [N("D3"), N("F3"), N("A3"), N("E4")]),
        ("Bb2", [N("Bb2"), N("D3"), N("F3"), N("A3")]),
        ("F2", [N("F2"), N("A2"), N("C3"), N("E3")]),
        ("C3", [N("C3"), N("E3"), N("G3"), N("D4")]),
    ]
    rng = np.random.default_rng(44)
    mel = _penta_melody(rng, 8, ["D", "F", "G", "A", "C"], density=0.45)
    base = compose_chill(64, 8, prog, mel, ep_vol=0.24, seed=44,
                         crackle_vol=0.006)
    rain = _noise(len(base) / SR, vol=0.05, alpha=0.5, seed=45)
    return _normalize(_seamless(base + rain[: len(base)]))


def music_shrine_story():
    # sacred stillness: Am - F - C - G, spacious koto
    prog = [
        ("A2", [N("A2"), N("C3"), N("E3")]),
        ("F2", [N("F2"), N("A2"), N("C3")]),
        ("C3", [N("C3"), N("E3"), N("G3")]),
        ("G2", [N("G2"), N("B2"), N("D3")]),
    ]
    rng = np.random.default_rng(55)
    mel = _penta_melody(rng, 8, ["A", "C", "D", "E", "G"], density=0.35, octv=5)
    return compose_chill(58, 8, prog, mel, ep_vol=0.20, pad_vol=0.07,
                         pluck_vol=0.22, sub_vol=0.16, seed=55,
                         echo_vol=0.22, ep_pattern=(0,))


def music_outskirts_danger():
    # mysterious night walk (soft tension, no harsh waves)
    prog = [
        ("A2", [N("A2"), N("C3"), N("E3")]),
        ("A2", [N("A2"), N("C3"), N("Eb3")]),
        ("F2", [N("F2"), N("Ab2"), N("C3")]),
        ("E2", [N("E2"), N("G#2"), N("B2")]),
    ]
    rng = np.random.default_rng(66)
    mel = _penta_melody(rng, 8, ["A", "C", "D", "Eb", "G"], density=0.4, octv=4)
    return compose_chill(62, 8, prog, mel, ep_vol=0.20, pad_vol=0.06,
                         pluck_vol=0.18, sub_vol=0.24, seed=66,
                         echo_vol=0.18, crackle_vol=0.016,
                         ep_pattern=(0, 1.5, 3.0))


# ------------------------------------------------------------- ambience
def amb_wind():
    n = 10.0
    base = _noise(n, vol=0.30, alpha=0.08)
    lfo = 0.5 + 0.5 * np.sin(2 * np.pi * np.arange(len(base)) / SR * 0.15)
    return _normalize(_seamless(base * (0.4 + 0.6 * lfo)), 0.6)


def amb_birds():
    rng = np.random.default_rng(21)
    out = _noise(12.0, vol=0.06, alpha=0.3, seed=21)
    t = 0.5
    while t < 11.0:
        f0 = rng.uniform(2800, 4200)
        n = int(SR * 0.12)
        tt = np.arange(n) / SR
        chirp = (np.sin(2 * np.pi * f0 * tt) * 0.20
                 + np.sin(2 * np.pi * f0 * 1.3 * tt) * 0.12)
        chirp *= np.minimum(1.0, tt / 0.02) * np.exp(-tt / 0.015)
        _place(out, chirp, t)
        if rng.random() < 0.5:
            _place(out, chirp, t + 0.18)
        t += rng.uniform(0.8, 2.4)
    return _normalize(_seamless(out), 0.6)


def amb_cicadas():
    n = int(SR * 10.0)
    t = np.arange(n) / SR
    buzz = np.sin(2 * np.pi * 5200 * t) * (0.5 + 0.5 * np.sign(np.sin(2 * np.pi * 28 * t)))
    swell = 0.5 + 0.5 * np.sin(2 * np.pi * t * 0.2)
    return _normalize(_seamless(buzz * swell * 0.25), 0.6)


def amb_crickets():
    rng = np.random.default_rng(33)
    out = np.zeros(int(SR * 10.0))
    t = 0.3
    while t < 9.5:
        for k in range(3):
            n = int(SR * 0.05)
            tt = np.arange(n) / SR
            sig = (np.sin(2 * np.pi * 4400 * tt) * 0.15
                   * np.minimum(1.0, tt / 0.01) * np.exp(-tt / 0.005))
            _place(out, sig, t + k * 0.09)
        t += rng.uniform(0.5, 1.1)
    return _normalize(_seamless(out), 0.6)


def amb_rain():
    return _normalize(_seamless(_noise(10.0, vol=0.35, alpha=0.5, seed=7)), 0.6)


def amb_water():
    n = 10.0
    base = _noise(n, vol=0.25, alpha=0.25, seed=7)
    lfo = 0.5 + 0.5 * np.sin(2 * np.pi * np.arange(len(base)) / SR * 0.4)
    return _normalize(_seamless(base * (0.3 + 0.7 * lfo)), 0.6)


def amb_train():
    n = int(SR * 12.0)
    t = np.arange(n) / SR
    rumble = _noise(12.0, vol=0.20, alpha=0.05, seed=7)
    swell = np.clip(np.sin(np.pi * t / 12.0), 0, 1) ** 2
    nn = int(SR * 1.2)
    tt = np.arange(nn) / SR
    horn = ((np.sin(2 * np.pi * 233 * tt) + np.sin(2 * np.pi * 175 * tt)) * 0.10
            * np.minimum(1.0, tt / 0.3) * np.exp(-tt / 1.5))
    out = rumble * (0.3 + 0.7 * swell)
    _place(out, horn, 4.0)
    return _normalize(_seamless(out), 0.6)


TRACKS = {
    "music_town_day": music_town_day,
    "music_town_dusk": music_town_dusk,
    "music_town_night": music_town_night,
    "music_town_rain": music_town_rain,
    "music_shrine_story": music_shrine_story,
    "music_outskirts_danger": music_outskirts_danger,
    "amb_wind": amb_wind,
    "amb_birds": amb_birds,
    "amb_cicadas": amb_cicadas,
    "amb_crickets": amb_crickets,
    "amb_rain": amb_rain,
    "amb_water": amb_water,
    "amb_train": amb_train,
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    os.makedirs(args.out, exist_ok=True)
    for name, fn in TRACKS.items():
        wav = os.path.join(args.out, name + ".wav")
        ogg = os.path.join(args.out, name + ".ogg")
        print("synth", name, flush=True)
        _write_wav(wav, fn())
        _to_ogg(wav, ogg)
        os.remove(wav)
    print("done ->", args.out)


if __name__ == "__main__":
    main()
